/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syscv.utd.presentacion;

import com.syscv.utd.conexionBD.ConexionBD;
import com.syscv.utd.dao.ctrlcom.documentos.ManejoImagen;
import com.syscv.utd.dao.ctrlcom.documentos.imagen;
import com.syscv.utd.dao.general.Dao_conductor;
import com.syscv.utd.entidades.Conductor;
import com.syscv.utd.entidades.ControllerItemList;
import com.syscv.utd.entidades.Tipo_Documentos_Vehi;
import com.syscv.utd.entidades.centro_costos;
import com.syscv.utd.entidades.itemcentrocostos;
import com.syscv.utd.recursos.JPColor;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jonathan
 */
public class JIFConductor extends javax.swing.JInternalFrame {

    private ConexionBD conexion=new ConexionBD();
    private int ccostos;

    private int itemcentro=0;
    private int id_usuario=MDIPrincipal.getvSeccion();
    private ManejoImagen mi=new ManejoImagen();
    private int id_tipo_doc;
    private int id_conductor;
    private int id_conductor_img;
    private int id_conductor_doc;
    private Conductor conductor;
    private Dao_conductor daoconductor;
    
    private DefaultListModel modListaImagen = new DefaultListModel();
    
    
    
    public JIFConductor() {
        
     
        initComponents();
        
        conexion=new ConexionBD();
        
        this.dc_inicio.setDate(new Date());
        this.dc_ven.setDate(new Date());
        
        Color c1=new Color(66,111,166);
        Color c2=new Color(102,174,118);
        JPColor miColor=new JPColor(c1,c2);
        miColor.setSize(this.getSize());
        p_encabezado.add(miColor);
        
        
        cargarCentroCostos();
                
        cargarItemTipoDoc();
        
        cargarConductor();
        

             
             
         
            
//          ResultSet obj2=conexion.executeQuery("SELECT (ma.descripcion ||' - '|| li.descripcion)AS linea FROM utilidades.linea_vehiculo li JOIN utilidades.marca_vehiculo ma ON ma.id_marca=li.id_marca ORDER BY linea ASC");
//
//                  while(obj2.next())
//            {
//                cb_linea.addItem(obj2.getObject("linea"));
//            }  
               
               
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        p_encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tp_general = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_cel = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_dir = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_jefe = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_eps = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_arl = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_cancelar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        cb_conductor = new javax.swing.JComboBox();
        btn_buscar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        cb_cc = new javax.swing.JComboBox();
        cb_item = new javax.swing.JComboBox();
        cbx_activo = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_registros = new javax.swing.JComboBox();
        btnadjuntar = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Imagenes = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        FOTO = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        cb_registros1 = new javax.swing.JComboBox();
        btnadjuntar1 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cb_tipo_doc = new javax.swing.JComboBox();
        dc_inicio = new com.toedter.calendar.JDateChooser();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        dc_ven = new com.toedter.calendar.JDateChooser();
        ck_box_ven = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        txt_ndoc = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txt_res = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txt_cat = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_Imagenes1 = new javax.swing.JList();
        jPanel11 = new javax.swing.JPanel();
        FOTO1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel6.setText("jLabel6");

        jLabel11.setText("jLabel11");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton2");

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Conductores --UTDVVCC--");

        p_encabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Registro Conductores");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/choferes.png"))); // NOI18N

        javax.swing.GroupLayout p_encabezadoLayout = new javax.swing.GroupLayout(p_encabezado);
        p_encabezado.setLayout(p_encabezadoLayout);
        p_encabezadoLayout.setHorizontalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(339, 339, 339))
        );
        p_encabezadoLayout.setVerticalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addGroup(p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_encabezadoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Nombre");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Apellido");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Cédula");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Celular");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Teléfono");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Dirección");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Jefe Inmediato");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("EPS");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("ARL");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("Centro Costos");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_cancelar1.setText("Cancelar");
        txt_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cancelar1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Conductor"));

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setText("Conductor");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(cb_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cb_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_actualizar.setText("Actualizar");
        btn_actualizar.setEnabled(false);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        cb_cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ccActionPerformed(evt);
            }
        });

        cbx_activo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbx_activo.setSelected(true);
        cbx_activo.setText("Activo Conductor");
        cbx_activo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbx_activo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cancelar1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cedula)
                                    .addComponent(txt_tel)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_arl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_jefe)
                                    .addComponent(cb_cc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_eps, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(txt_dir, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_apellido, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(19, 19, 19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txt_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txt_arl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(cb_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txt_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txt_eps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(cbx_activo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(txt_cancelar1)
                    .addComponent(btn_actualizar))
                .addContainerGap())
        );

        tp_general.addTab("Conductor", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjuntar archivos"));

        jLabel3.setText("Conductor");

        cb_registros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cb_registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_registrosActionPerformed(evt);
            }
        });

        btnadjuntar.setText("Adjuntar");
        btnadjuntar.setToolTipText("Nota: Solo se admiten archivos JPG de peso maximo 1 Mb. Se recomiendan archivos de resolución 800 x 600 pixeles");
        btnadjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadjuntarActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 51, 51));
        jLabel37.setText("Nota: Solo se permiten archivos formato imagen (JPG). Y Tamaño max a (200 kb).  ");

        jLabel39.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 51, 51));
        jLabel39.setText("El nombre del archivo deber ser la placa del vehiculo/Equipo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnadjuntar))
                    .addComponent(jLabel37)
                    .addComponent(jLabel39))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnadjuntar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 300));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        Lista_Imagenes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista_Imagenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_ImagenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lista_Imagenes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(320, 300));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        FOTO.setText("FOTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel7.add(FOTO, gridBagConstraints);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tp_general.addTab("Subir Foto", jPanel4);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjuntar archivos"));

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setText("Conductor  *");

        cb_registros1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cb_registros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_registros1ActionPerformed(evt);
            }
        });

        btnadjuntar1.setText("Adjuntar");
        btnadjuntar1.setToolTipText("Nota: Solo se admiten archivos JPG de peso maximo 1 Mb. Se recomiendan archivos de resolución 800 x 600 pixeles");
        btnadjuntar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadjuntar1ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 51, 51));
        jLabel41.setText("Nota: Solo se permiten archivos formato imagen (JPG). Y Tamaño max a (500 kb).  ");

        jLabel42.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 51, 51));
        jLabel42.setText("El nombre del archivo deber ser la Inicial Nombre y apellido.");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel43.setText("Tipo de Doc *");

        cb_tipo_doc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        dc_inicio.setEnabled(false);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setText("Fecha Inicio");

        jLabel45.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel45.setText("Fecha Vencimiento");

        dc_ven.setEnabled(false);

        ck_box_ven.setText("Doc. tiene Vencimiento");
        ck_box_ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_box_venActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setText("N° de Documento *");

        jLabel47.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 51, 51));
        jLabel47.setText("* Campos Obligatorios");

        jLabel48.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel48.setText("Restricción ");

        jLabel49.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel49.setText("Categoria *");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGap(0, 123, Short.MAX_VALUE)
                                .addComponent(jLabel43)
                                .addGap(18, 18, 18)
                                .addComponent(cb_tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_res, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(10, 10, 10)
                                .addComponent(cb_registros1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel41)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dc_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dc_ven, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ck_box_ven))
                            .addComponent(jLabel42))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnadjuntar1)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_registros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel43)
                    .addComponent(cb_tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)
                            .addComponent(txt_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(txt_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel44)
                                .addComponent(dc_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel45)
                                .addComponent(dc_ven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ck_box_ven))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnadjuntar1))))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 300));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        Lista_Imagenes1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista_Imagenes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_Imagenes1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Lista_Imagenes1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel10.add(jScrollPane2, gridBagConstraints);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(320, 300));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        FOTO1.setText("DOCUMENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel11.add(FOTO1, gridBagConstraints);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)))
        );

        tp_general.addTab("Documentación", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tp_general)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_general))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_registrosActionPerformed
        Actualizar_lista();
    }//GEN-LAST:event_cb_registrosActionPerformed

    private void btnadjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadjuntarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter( new FileNameExtensionFilter("Archivo de Imagen","jpg") );
        fileChooser.setCurrentDirectory(new java.io.File("e:/imagenes_tmp/"));
        int result = fileChooser.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ){
            //obtiene ruta y nombre del archivo
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            String name = fileChooser.getSelectedFile().getName();
            Conductor c=(Conductor) cb_registros.getSelectedItem();
            id_conductor_img=c.getId_conductor();
            conexion=new ConexionBD();
            try {
                
                ResultSet obj =conexion.executeQuery("SELECT foto FROM utilidades.conductor WHERE foto=true AND id_conductor="+id_conductor_img+"");
                
                        
                        if (obj.next()==true)
                        {
                            JOptionPane.showMessageDialog(rootPane, "No se puede cargar la foto. El vehiculo/Equpo ya tiene foto asignada.");
                        }
                  else
                        {
                if( mi.guardarfotoCon(GenerarCodigo() , name, ruta, id_conductor_img) )
                {
                    JOptionPane.showMessageDialog(this,"Documento ["+name+"] almacenado");
                    Actualizar_lista();
                   
                    
                    conexion.executeUpdateQuery("UPDATE utilidades.conductor SET foto=true WHERE id_conductor="+id_conductor_img+"");
                    conexion.desconectar();
                 
                }
              } 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnadjuntarActionPerformed

    private void Lista_ImagenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_ImagenesMouseClicked
        int index = this.Lista_Imagenes.getSelectedIndex();//obtiene index seleccionado
        if( index != -1)
        {
            //Extrae la clase imagen que corresponde a la posición donde se hizo un clic
            imagen img = (imagen)this.modListaImagen.getElementAt(index);
            //redimensiona imagen

            double alto = img.getArchivo().getHeight(null) / Math.ceil(img.getArchivo().getHeight(null)/300f) ;
            double ancho =img.getArchivo().getWidth(null) / Math.ceil(img.getArchivo().getWidth(null)/500f) ;
            Icon icon = new ImageIcon( img.getArchivo().getScaledInstance((int)ancho,(int)alto, Image.SCALE_AREA_AVERAGING) );
            this.FOTO.setText("");
            this.FOTO.setIcon( icon  );//coloca imagen en el JLabel
        }

    }//GEN-LAST:event_Lista_ImagenesMouseClicked

    private void cb_registros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_registros1ActionPerformed
        Actualizar_lista2();
    }//GEN-LAST:event_cb_registros1ActionPerformed

    private void btnadjuntar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadjuntar1ActionPerformed
       
        
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter( new FileNameExtensionFilter("Archivo de Imagen","jpg") );
        fileChooser.setCurrentDirectory(new java.io.File("e:/imagenes_tmp/"));
        int result = fileChooser.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ){
            //obtiene ruta y nombre del archivo
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            String name = fileChooser.getSelectedFile().getName();
            
            Tipo_Documentos_Vehi t=(Tipo_Documentos_Vehi) cb_tipo_doc.getSelectedItem();
            id_tipo_doc=t.getId_tipo_doc();
            
            Conductor c=(Conductor) cb_registros1.getSelectedItem();
            id_conductor_doc=c.getId_conductor();
            
            Date fecha_ini=dc_inicio.getDate();
            Date fecha_vence=dc_ven.getDate();
            
            java.sql.Date sqlFecha_ini = new java.sql.Date(fecha_ini.getTime());
            java.sql.Date sqlFecha_vence = new java.sql.Date(fecha_vence.getTime());
            String cat = txt_cat.getText();
            String rest=txt_res.getText();

            
            
            String n_doc=txt_ndoc.getText();
            
            boolean vence=false;
            
            if(ck_box_ven.isSelected())
            {
                vence=true;
            }
            
            
           
            try {
                
                ResultSet obj =conexion.executeQuery("SELECT id FROM utilidades.doc_conductor WHERE id_conductor="+id_conductor_doc+" AND activo=true");
                
                        
                        if (obj.next()==true)
                        {
                            JOptionPane.showMessageDialog(rootPane, "No se puede cargar el documento. El Conductor ya tiene asignado este tipo de documento y esta vigente");
                        }
                  else
                        {
                            
                            
                            
                if( mi.guardarDoc_Conductor(GenerarCodigo() , name, ruta,id_conductor_doc, vence,id_tipo_doc,id_usuario, sqlFecha_ini, sqlFecha_vence,n_doc, cat, rest ) )
                {
                    JOptionPane.showMessageDialog(this,"Documento ["+name+"] almacenado");
                    Actualizar_lista2();
                    limpiarModDoc();
                   
                    
                    conexion.desconectar();
                 
                }
              } 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnadjuntar1ActionPerformed

    private void Lista_Imagenes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_Imagenes1MouseClicked
        int index = this.Lista_Imagenes1.getSelectedIndex();//obtiene index seleccionado
        if( index != -1)
        {
            //Extrae la clase imagen que corresponde a la posición donde se hizo un clic
            imagen img = (imagen)this.modListaImagen.getElementAt(index);
            //redimensiona imagen

            double alto = img.getArchivo().getHeight(null) / Math.ceil(img.getArchivo().getHeight(null)/300f) ;
            double ancho =img.getArchivo().getWidth(null) / Math.ceil(img.getArchivo().getWidth(null)/1000f) ;
            Icon icon = new ImageIcon( img.getArchivo().getScaledInstance((int)ancho,(int)alto, Image.SCALE_AREA_AVERAGING) );
            this.FOTO1.setText("");
            this.FOTO1.setIcon( icon  );//coloca imagen en el JLabel
        }

    }//GEN-LAST:event_Lista_Imagenes1MouseClicked

    private void ck_box_venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_box_venActionPerformed
        
        if(ck_box_ven.isSelected())
        {
            dc_inicio.setEnabled(true);
            dc_ven.setEnabled(true);
        }
        else
        {
            dc_inicio.setEnabled(false);
            dc_ven.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_ck_box_venActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        itemcentrocostos item=(itemcentrocostos)cb_item.getSelectedItem();
        itemcentro=item.getId_item();
     
        Conductor c=new Conductor();
        daoconductor=new Dao_conductor();

        String nombre, apellido, tel, cel, direccion, jefe, eps, arl;
        long cedula=0;
        Date fecha_mod=new Date();
        
        
       nombre=txt_nombre.getText();
       apellido=txt_apellido.getText();
       tel=txt_tel.getText();
       cel=txt_cel.getText();
       direccion=txt_dir.getText();
       jefe=txt_jefe.getText();
       eps=txt_eps.getText();
       arl=txt_arl.getText();
       cedula=Long.parseLong(txt_cedula.getText());
       
       
       c.setNombre(nombre);
       c.setApellido(apellido);
       c.setCedula(cedula);
       c.setArl(arl);
       c.setCel(cel);
       c.setDir(direccion);
       c.setEps(eps);
       c.setFecha_mod(fecha_mod);
       c.setId_area(itemcentro);
       c.setId_conductor(id_conductor);
       c.setJefe_inmediato(jefe);
       c.setTel(tel);
       c.setId_usuario_mod(id_usuario);
       
       
       if(cbx_activo.isSelected())
       {
           c.setActivo(true);
       }
       else
       {
           c.setActivo(false);
       }

        try {
            daoconductor.actualizar(c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,  ex);
        }

        conexion.desconectar();

        limpiar();
        cb_conductor.setEnabled(true);
        btn_actualizar.setEnabled(false);
        cbx_activo.setEnabled(false);

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        
        
       Conductor con=(Conductor)cb_conductor.getSelectedItem();
       id_conductor=con.getId_conductor();
       
        buscarConductor(id_conductor);
   
        cb_conductor.setEnabled(false);
        btn_actualizar.setEnabled(true);
        
        cbx_activo.setEnabled(true);
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_txt_cancelar1ActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
            conductor=new Conductor();
            daoconductor= new Dao_conductor();
            
            
            itemcentrocostos item=(itemcentrocostos)cb_item.getSelectedItem();
            itemcentro=item.getId_item();
            
            
            
            conductor.setCedula(Long.parseLong(txt_cedula.getText()));
            conductor.setNombre(txt_nombre.getText());
            conductor.setApellido(txt_apellido.getText());
            conductor.setCel(txt_cel.getText());
            conductor.setTel(txt_tel.getText());
            conductor.setEps(txt_eps.getText());
            conductor.setArl(txt_arl.getText());
            conductor.setId_usuario(id_usuario);
            conductor.setJefe_inmediato(txt_jefe.getText());
            conductor.setDir(txt_dir.getText());
            conductor.setId_area(itemcentro);
            
        try {
            daoconductor.guardar(conductor);
            limpiar();
            cargarConductor();
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
            
            
            
            
            
                    

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void cb_ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ccActionPerformed
        centro_costos costos=(centro_costos) cb_cc.getSelectedItem();
        
        ccostos=costos.getId_centro();
        
        cb_item.removeAllItems();
        cargarItemCentroCostos(ccostos);
        
    }//GEN-LAST:event_cb_ccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FOTO;
    private javax.swing.JLabel FOTO1;
    private javax.swing.JList Lista_Imagenes;
    private javax.swing.JList Lista_Imagenes1;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btnadjuntar;
    private javax.swing.JButton btnadjuntar1;
    private javax.swing.JComboBox cb_cc;
    private javax.swing.JComboBox cb_conductor;
    private javax.swing.JComboBox cb_item;
    private javax.swing.JComboBox cb_registros;
    private javax.swing.JComboBox cb_registros1;
    private javax.swing.JComboBox cb_tipo_doc;
    private javax.swing.JCheckBox cbx_activo;
    private javax.swing.JCheckBox ck_box_ven;
    private com.toedter.calendar.JDateChooser dc_inicio;
    private com.toedter.calendar.JDateChooser dc_ven;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_encabezado;
    private javax.swing.JTabbedPane tp_general;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_arl;
    private javax.swing.JButton txt_cancelar1;
    private javax.swing.JTextField txt_cat;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_cel;
    private javax.swing.JTextField txt_dir;
    private javax.swing.JTextField txt_eps;
    private javax.swing.JTextField txt_jefe;
    private javax.swing.JTextField txt_ndoc;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_res;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables

    
      
      public void limpiar()
      {
         
         txt_nombre.setText("");
         txt_apellido.setText("");
         txt_cedula.setText("");
         txt_cel.setText("");
         txt_tel.setText("");
         txt_dir.setText("");
         txt_jefe.setText("");
         txt_eps.setText("");
         txt_arl.setText("");
         
      }
      
      
          public void cargarItemVehiculo()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemVehiculo();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_conductor.addItem(lista.get(i));
                cb_registros.addItem(lista.get(i));
                cb_registros1.addItem(lista.get(i));
            }
        }
    }
          
          
            public void cargarItemTipoDoc()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarIteTipoDoc();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_tipo_doc.addItem(lista.get(i));
                
            }
        }
    }
            
        public void cargarCentroCostos()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarCentroCostos();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_cc.addItem(lista.get(i));
            
              
            }
        }
    }      
          
          
          
       public void cargarItemCentroCostos(int id)
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemCentroCostos(id);
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_item.addItem(lista.get(i));
            
              
            }
        }
    }     
            
            

    public void buscarConductor(int id_conductor)
    {
        
        
       String nombre="",apellido="", tel="",cel="", jefe="", direccion="", eps="", arl="";
       long cedula = 0;
       
        
       ResultSet obj=conexion.executeQuery("SELECT id_conductor,cedula, nombre, apellido, celular, tel, jefe_inmediato, direccion, eps,arl FROM utilidades.conductor WHERE id_conductor="+id_conductor+"");
        
        
        
        try {
            if(obj.next()==true)
            {
                cedula=obj.getLong("cedula");
                nombre=obj.getString("nombre");
                apellido=obj.getString("apellido");
                cel=obj.getString("celular");
                tel=obj.getString("tel");
                jefe=obj.getString("jefe_inmediato");
                direccion=obj.getString("direccion");
                eps=obj.getString("eps");
                arl=obj.getString("arl");
        
                        
            }
            
           
         txt_nombre.setText(nombre);
         txt_apellido.setText(apellido);
         txt_cedula.setText(String.valueOf(cedula));
         txt_cel.setText(cel);
         txt_tel.setText(tel);
         txt_dir.setText(direccion);
         txt_jefe.setText(jefe);
         txt_eps.setText(eps);
         txt_arl.setText(arl);
     
     
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(JIFConductor.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
         
     private void Actualizar_lista()
    {
        
        Conductor c=(Conductor) cb_registros.getSelectedItem();
        id_conductor_img=c.getId_conductor();
        this.modListaImagen.clear();
        this.modListaImagen = mi.Lista_Fot_Conductor(id_conductor_img);
        this.Lista_Imagenes.setModel(modListaImagen);
    }
     
      private void Actualizar_lista2()
    {
        
        Conductor c=(Conductor) cb_registros1.getSelectedItem();
        id_conductor_doc=c.getId_conductor();
        this.modListaImagen.clear();
        this.modListaImagen = mi.Lista_Doc_Conductor(id_conductor_doc);
        this.Lista_Imagenes1.setModel(modListaImagen);
    }

      //Genera un código unico para la imagen
    private String GenerarCodigo()
    {
        SimpleDateFormat sdf= new SimpleDateFormat("hhmmss");
        return sdf.format(new Date());
    }
    
         public void cargarConductor()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarConductor();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_conductor.addItem(lista.get(i));
                cb_registros.addItem(lista.get(i));
                cb_registros1.addItem(lista.get(i));
            
              
            }
        }
    }    
         
         
         public void limpiarModDoc()
         {
             txt_res.setText("");
             txt_ndoc.setText("");
             txt_cat.setText("");
             dc_inicio.setDate(new Date());
             dc_ven.setDate(new Date());
         }


}
