/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syscv.utd.presentacion;

import com.syscv.utd.conexionBD.ConexionBD;
import com.syscv.utd.dao.ctrlcom.ConsumoEstacionDao;
import com.syscv.utd.dao.ctrlcom.DetalleCEDao;
import com.syscv.utd.entidades.Consumo_Estacion;
import com.syscv.utd.entidades.ControllerItemList;
import com.syscv.utd.entidades.Detalle_Consumo_Estacion;
import com.syscv.utd.entidades.Vehiculo;
import com.syscv.utd.recursos.JPColor;
import com.syscv.utd.reportes.ReporteConEstacion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jonathan
 */
public class JIFConsumoEstacion extends javax.swing.JInternalFrame {

       private ConexionBD conexion=new ConexionBD();
       private int idusuario=MDIPrincipal.getvSeccion();
       private DefaultTableModel modelo;
       private Consumo_Estacion ce;
       private ConsumoEstacionDao ceDao;
       private Detalle_Consumo_Estacion detce;
       private DetalleCEDao detceDao;
       private int idce;
       private int id_vehiculo=0;
       private int id_tabla;
       private ReporteConEstacion reporte;
       private JIFVehiculosEquipos vehiculos;
       

    public JIFConsumoEstacion() throws SQLException {
        initComponents();
        
        Color c1=new Color(66,111,166);
        Color c2=new Color(102,174,118);
        JPColor miColor=new JPColor(c1,c2);
        miColor.setSize(this.getSize());
        p_encabezado.add(miColor);
        
        cargarItemVehiculo();
        
         ResultSet obj=conexion.executeQuery("SELECT est_ser_desc FROM utilidades.estaciones_servicio ORDER BY est_ser_desc");
        
        while(obj.next())
        {
            cb_estacion.addItem(obj.getObject("est_ser_desc"));
            

        }
        
//        ResultSet obj1=conexion.executeQuery("SELECT name_combustible FROM utilidades.tipo_combustible ORDER BY name_combustible");
//        
//        while (obj1.next())
//        {
//            cb_tc.addItem(obj1.getObject("name_combustible"));
//            cb_tc1.addItem(obj1.getObject("name_combustible"));
//
//        }
        
        
        ResultSet obj2=conexion.executeQuery("SELECT MAX(id_ce)+1 as id  FROM consumo_combustible.consumo_estacion");
       
       while(obj2.next())
       {
           txt_id.setText(String.valueOf(obj2.getInt("id")));//Le asigna el consecutivo siguiente de orden compra al textfield
       }
        
        conexion.desconectar();
        
        
        modelo=new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Fecha");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Vale UTD");
        modelo.addColumn("Vale EDS");      
        modelo.addColumn("Combustible");
        modelo.addColumn("Cantidad Gal");
        modelo.addColumn("Valor Gal");
        modelo.addColumn("Total");
        modelo.addColumn("Kilometraje");
        modelo.addColumn("Obse");
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        JD_Agregar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_eds = new javax.swing.JTextField();
        dc_fechaTan = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_cg = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_km = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cb_vehi = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        cb_tc = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        txta_obse2 = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_vale_utd = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_agregarvehi = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JD_Mod = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_eds1 = new javax.swing.JTextField();
        dc_fechaTan1 = new com.toedter.calendar.JDateChooser();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_cg1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_km1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txt_precio1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        cb_vehi1 = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        cb_tc1 = new javax.swing.JComboBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        txta_obse3 = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        btn_guardar1 = new javax.swing.JButton();
        txt_vale_utd1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        btn_cancelar1 = new javax.swing.JButton();
        btn_agregarvehi2 = new javax.swing.JButton();
        btn_actualizar1 = new javax.swing.JButton();
        p_encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_numcta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dc_fechaven = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cb_estacion = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_obse = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_detalle = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_terminar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        JD_Agregar.setTitle("Detalle Consumo x Estación --UTD--");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel21.setText("Número Vale UTD *");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel22.setText("Número Recibo EDS *");

        txt_eds.setText("000-000");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel23.setText("Fecha Tanqueo *");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel24.setText("Cantidad Combustible *");

        txt_cg.setText("0");

        jLabel25.setText("gal");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel26.setText("KM /h al tanqueo *");

        txt_km.setText("0");

        jLabel27.setText("km /h");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel28.setText("Total Tanqueo $ *");

        txt_precio.setText("0");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel29.setText("Vehiculo*");

        cb_vehi.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        cb_vehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vehiActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel30.setText("Tipo Combustible *");

        txta_obse2.setColumns(20);
        txta_obse2.setRows(5);
        jScrollPane5.setViewportView(txta_obse2);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel31.setText("Observaciones");

        btn_guardar.setText("Agregar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_vale_utd.setText("0");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 0));
        jLabel32.setText("* Campos Obligatorios");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_agregarvehi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/add.png"))); // NOI18N
        btn_agregarvehi.setToolTipText("Registro de vehiculos");
        btn_agregarvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarvehiActionPerformed(evt);
            }
        });

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/actualizar.png"))); // NOI18N
        btn_actualizar.setToolTipText("Actualizar Lista de vehiculos / Equipos");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cancelar))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cb_vehi, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btn_agregarvehi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_eds, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel30)
                                        .addComponent(jLabel23))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dc_fechaTan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cb_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel27))))))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_vale_utd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(cb_vehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addComponent(btn_agregarvehi)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(7, 7, 7))
                    .addComponent(dc_fechaTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txt_vale_utd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_eds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel31))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(txt_cg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_guardar)
                    .addComponent(jLabel32))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_AgregarLayout = new javax.swing.GroupLayout(JD_Agregar.getContentPane());
        JD_Agregar.getContentPane().setLayout(JD_AgregarLayout);
        JD_AgregarLayout.setHorizontalGroup(
            JD_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AgregarLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JD_AgregarLayout.setVerticalGroup(
            JD_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AgregarLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel33.setText("Número Vale UTD *");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel34.setText("Número Recibo EDS *");

        txt_eds1.setText("000-000");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel35.setText("Fecha Tanqueo *");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel36.setText("Cantidad Combustible *");

        txt_cg1.setText("0");

        jLabel37.setText("gal");

        jLabel38.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel38.setText("KM /H al tanqueo *");

        txt_km1.setText("0");

        jLabel39.setText("km/h");

        jLabel40.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel40.setText("Total Tanqueo $ *");

        txt_precio1.setText("0");

        jLabel41.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel41.setText("Vehiculo*");

        cb_vehi1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        cb_vehi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vehi1ActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel42.setText("Tipo Combustible *");

        txta_obse3.setColumns(20);
        txta_obse3.setRows(5);
        jScrollPane6.setViewportView(txta_obse3);

        jLabel43.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel43.setText("Observaciones");

        btn_guardar1.setText("Agregar");
        btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar1ActionPerformed(evt);
            }
        });

        txt_vale_utd1.setText("0");

        jLabel44.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(153, 0, 0));
        jLabel44.setText("* Campos Obligatorios");

        btn_cancelar1.setText("Cancelar");
        btn_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar1ActionPerformed(evt);
            }
        });

        btn_agregarvehi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/add.png"))); // NOI18N
        btn_agregarvehi2.setToolTipText("Registro de vehiculos");
        btn_agregarvehi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarvehi2ActionPerformed(evt);
            }
        });

        btn_actualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/actualizar.png"))); // NOI18N
        btn_actualizar1.setToolTipText("Actualizar Lista de vehiculos / Equipos");
        btn_actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar1)
                        .addGap(3, 3, 3)
                        .addComponent(btn_cancelar1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane6))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_vehi1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_agregarvehi2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_eds1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_vale_utd1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_tc1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dc_fechaTan1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cg1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38)
                        .addGap(33, 33, 33)
                        .addComponent(txt_km1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(cb_vehi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_agregarvehi2)
                    .addComponent(btn_actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_tc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel35)
                                .addComponent(dc_fechaTan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(txt_eds1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txt_vale_utd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(txt_cg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(jLabel40)
                        .addComponent(txt_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel38))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_km1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel43)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(btn_guardar1)
                    .addComponent(btn_cancelar1))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout JD_ModLayout = new javax.swing.GroupLayout(JD_Mod.getContentPane());
        JD_Mod.getContentPane().setLayout(JD_ModLayout);
        JD_ModLayout.setHorizontalGroup(
            JD_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ModLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JD_ModLayout.setVerticalGroup(
            JD_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consumo x Estación  --UTDVVCC--");

        p_encabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Consumo Por Estación de Servicio");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/medidor.png"))); // NOI18N

        javax.swing.GroupLayout p_encabezadoLayout = new javax.swing.GroupLayout(p_encabezado);
        p_encabezado.setLayout(p_encabezadoLayout);
        p_encabezadoLayout.setHorizontalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(263, 263, 263))
        );
        p_encabezadoLayout.setVerticalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addGroup(p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(p_encabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jLabel2.setText("ID CEDS");

        txt_id.setEditable(false);

        jLabel3.setText("Número Cta. Suministro *");

        jLabel4.setText("Fecha Vencimiento *");

        jLabel5.setText("Estación *");

        jLabel6.setText("Observaciones");

        txta_obse.setColumns(20);
        txta_obse.setRows(5);
        jScrollPane1.setViewportView(txta_obse);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 0));
        jLabel19.setText("* Campos Obligatorios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_numcta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dc_fechaven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_estacion, 0, 200, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dc_fechaven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txt_numcta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cb_estacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        t_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(t_detalle);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/add.png"))); // NOI18N
        btn_agregar.setToolTipText("Agregar Item");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/delete_1.png"))); // NOI18N
        btn_eliminar.setToolTipText("Eliminar Item");
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/mod_detalle.png"))); // NOI18N
        btn_mod.setToolTipText("Modificar Item");
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_agregar)
                        .addGap(1, 1, 1)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mod))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_terminar.setText("Terminar");
        btn_terminar.setEnabled(false);
        btn_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_terminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
       
        try
        {
        
        ce=new Consumo_Estacion();
        ceDao=new ConsumoEstacionDao();
        detce=new Detalle_Consumo_Estacion();
        detceDao=new DetalleCEDao();
        int ideds=0;
        int idtipocom=0;
        int vlorGas=0;
        //int kilometraje=0;
        
       
        
      ResultSet obj0=conexion.executeQuery("SELECT id_ce FROM consumo_combustible.consumo_estacion WHERE id_ce="+txt_id.getText()+"");
     
       if(obj0.next()==false)
      {
          
      
        ce.setFecha_informe(new Date());
        ce.setNumero_cta(txt_numcta.getText());
        ce.setFecha_vencer(dc_fechaven.getDate());
         if(cb_estacion.getSelectedItem()!= null)
        {
            String eds=cb_estacion.getSelectedItem().toString();
            
            ResultSet obj=conexion.executeQuery("SELECT est_ser_id FROM utilidades.estaciones_servicio WHERE est_ser_desc='"+eds+"'");
            
            while (obj.next())
            {
                ideds=obj.getInt("est_ser_id");
                
            }
        }
         
         ce.setId_estacion(ideds);
         
        ce.setId_usuario(idusuario);
        ce.setObse(txta_obse.getText());
        ceDao.guardar(ce);
        
         bloquear();
        
        idce=ConsumoEstacionDao.getIdCEstacion();
        
        txt_id.setText(String.valueOf(idce));
        //Detalle//
        detce.setId_ce(idce);
        detce.setValeUtd(Integer.parseInt(txt_vale_utd.getText()));
        detce.setValeEstacion(txt_eds.getText());
        
        if(cb_tc.getSelectedItem()!=null)
        {
            String combus=cb_tc.getSelectedItem().toString();
            
            ResultSet obj1=conexion.executeQuery("SELECT id_tipo_com FROM utilidades.tipo_combustible WHERE name_combustible='"+combus+"'");
            
            while(obj1.next())
            {
                idtipocom=obj1.getInt("id_tipo_com");
            }
        
        }
        detce.setId_tipo_com(idtipocom);
        detce.setCant_gal(Float.parseFloat(txt_cg.getText()));
        detce.setValorTotal(Integer.parseInt(txt_precio.getText()));
        
//        ResultSet obj01=conexion.executeQuery("SELECT det.kmtanq AS km FROM consumo_combustible.det_con_eds det JOIN consumo_combustible.consumo_estacion ce ON ce.id_ce=det.id_ceds WHERE det.id_vehiculo="+id_vehiculo+" ORDER BY det.id_det_ceds DESC limit 1");
//         System.out.println(id_vehiculo);
//
//         while (obj01.next())
//         {
//             kilometraje=obj01.getInt("km");
//             System.out.println(kilometraje);
//         }
//         
//        if(Integer.parseInt(txt_km.getText()) <= kilometraje)
//        {
//           throw new Exception ("El kilometraje digitado no puede ser inferior a " + kilometraje+ " km");
//
//        }
        
        detce.setKilometraje(Float.parseFloat(txt_km.getText()));
        vlorGas=(int) (detce.getValorTotal()/detce.getCant_gal());
        detce.setVlorGalon(vlorGas);
        
        Vehiculo v=(Vehiculo) cb_vehi.getSelectedItem();
        id_vehiculo=v.getId_vehiculo();
        
        
       
        detce.setId_vehi(id_vehiculo);
        detce.setObse(txta_obse2.getText());
        detce.setFechaTanq(dc_fechaTan.getDate());
        
        detceDao.guardar(detce);
        limpiar();
        LimpiarTabla();
        detalleTabla();
       
      }
       else
       {
        detce.setId_ce(idce);
        detce.setValeUtd(Integer.parseInt(txt_vale_utd.getText()));
        detce.setValeEstacion(txt_eds.getText());
        
        if(cb_tc.getSelectedItem()!=null)
        {
            String combus=cb_tc.getSelectedItem().toString();
            
            ResultSet obj1=conexion.executeQuery("SELECT id_tipo_com FROM utilidades.tipo_combustible WHERE name_combustible='"+combus+"'");
            
            while(obj1.next())
            {
                idtipocom=obj1.getInt("id_tipo_com");
            }
        
        }
        
        detce.setId_tipo_com(idtipocom);
        detce.setCant_gal(Float.parseFloat(txt_cg.getText()));
        detce.setValorTotal(Integer.parseInt(txt_precio.getText()));
        
//         ResultSet obj01=conexion.executeQuery("SELECT det.kmtanq AS km FROM consumo_combustible.det_con_eds det JOIN consumo_combustible.consumo_estacion ce ON ce.id_ce=det.id_ceds WHERE det.id_vehiculo="+id_vehiculo+" ORDER BY det.id_det_ceds DESC limit 1");
//         System.out.println(id_vehiculo);
//
//         while (obj01.next())
//         {
//             kilometraje=obj01.getInt("km");
//             System.out.println(kilometraje);
//         }
//         
//        if(Integer.parseInt(txt_km.getText()) <= kilometraje)
//        {
//           throw new Exception ("El kilometraje digitado no puede ser inferior a " + kilometraje+ " km");
//
//        }
//        
//        
        
        detce.setKilometraje(Float.parseFloat(txt_km.getText()));
        vlorGas=(int) (detce.getValorTotal()/detce.getCant_gal());
        detce.setVlorGalon(vlorGas);
        
        
        Vehiculo v=(Vehiculo) cb_vehi.getSelectedItem();
        
        id_vehiculo=v.getId_vehiculo();
        
        detce.setId_vehi(id_vehiculo);
        detce.setObse(txta_obse2.getText());
        detce.setFechaTanq(dc_fechaTan.getDate());
        
        detceDao.guardar(detce);
        limpiar();
        LimpiarTabla();
        detalleTabla();
       }
        
       
               
       
       }catch(Exception e)
       {
         JOptionPane.showMessageDialog(this,"Error "+e, "Error",JOptionPane.ERROR_MESSAGE);

       }
         
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        JD_Agregar.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       JD_Agregar.pack();
       JD_Agregar.setLocationRelativeTo(null);
       JD_Agregar.setVisible(true);
       JD_Agregar.setResizable(false);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
         int opc=JOptionPane.showConfirmDialog(null,"Desea eliminar una Linea?", "Aviso!", JOptionPane.YES_NO_OPTION); 
          
        if(opc==JOptionPane.YES_OPTION)
        {
             eliminarRegistroTabla();
        }
       
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar1ActionPerformed
       try
       {
        detce=new Detalle_Consumo_Estacion();
        detceDao=new DetalleCEDao();
        int idtipocom=0;
        int vlorGas=0;
      //  int kilometraje=0;
           
           
        detce.setId_detalle(id_tabla);
        detce.setValeUtd(Integer.parseInt(txt_vale_utd1.getText()));
        detce.setValeEstacion(txt_eds1.getText());
        
        if(cb_tc1.getSelectedItem()!=null)
        {
            String combus=cb_tc1.getSelectedItem().toString();
            
            ResultSet obj1=conexion.executeQuery("SELECT id_tipo_com FROM utilidades.tipo_combustible WHERE name_combustible='"+combus+"'");
            
            while(obj1.next())
            {
                idtipocom=obj1.getInt("id_tipo_com");
            }
        
        }
        
        detce.setId_tipo_com(idtipocom);
        detce.setCant_gal(Float.parseFloat(txt_cg1.getText()));
        detce.setValorTotal(Integer.parseInt(txt_precio1.getText()));
        
//         ResultSet obj01=conexion.executeQuery("SELECT det.kmtanq AS km FROM consumo_combustible.det_con_eds det JOIN consumo_combustible.consumo_estacion ce ON ce.id_ce=det.id_ceds WHERE det.id_vehiculo="+id_vehiculo+" ORDER BY det.id_det_ceds DESC limit 1");
//         System.out.println(id_vehiculo);
//
//         while (obj01.next())
//         {
//             kilometraje=obj01.getInt("km");
//             System.out.println(kilometraje);
//         }
//         
//        if(Integer.parseInt(txt_km.getText()) <= kilometraje)
//        {
//           throw new Exception ("El kilometraje digitado no puede ser inferior a " + kilometraje+ " km");
//
//        }
        
        
        detce.setKilometraje(Float.parseFloat(txt_km1.getText()));
        vlorGas=(int) (detce.getValorTotal()/detce.getCant_gal());
        detce.setVlorGalon(vlorGas);
        
        Vehiculo v=(Vehiculo) cb_vehi1.getSelectedItem();
        id_vehiculo=v.getId_vehiculo();
      
        detce.setId_vehi(id_vehiculo);
        detce.setObse(txta_obse3.getText());
        detce.setFechaTanq(dc_fechaTan1.getDate());
        
        detceDao.actualizar(detce);
        limpiar();
        LimpiarTabla();
        detalleTabla();
      
       }catch(Exception e)
       {
         JOptionPane.showMessageDialog(this,"Error "+e, "Error",JOptionPane.ERROR_MESSAGE);

       }
    }//GEN-LAST:event_btn_guardar1ActionPerformed

    private void btn_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar1ActionPerformed
        JD_Mod.dispose();
    }//GEN-LAST:event_btn_cancelar1ActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
       
        int valeutd,valor_total;
        String valeeds,obse;
        float cant_gal,kilometraje;
        Date fechatanq;
        
        
         if(t_detalle.isRowSelected(t_detalle.getSelectedRow()))
            {
               id_tabla = (Integer) t_detalle.getValueAt(t_detalle.getSelectedRow(), 0);    
               fechatanq=(Date) t_detalle.getValueAt(t_detalle.getSelectedRow(),1);
               valeutd= (int) t_detalle.getValueAt(t_detalle.getSelectedRow(),3);
               valeeds=(String) t_detalle.getValueAt(t_detalle.getSelectedRow(),4);
               cant_gal=(float) t_detalle.getValueAt(t_detalle.getSelectedRow(),6);
               valor_total= (int) t_detalle.getValueAt(t_detalle.getSelectedRow(),8);
               kilometraje= (Float) t_detalle.getValueAt(t_detalle.getSelectedRow(),9);
               obse= (String) t_detalle.getValueAt(t_detalle.getSelectedRow(),10);
               
               
               dc_fechaTan1.setDate(fechatanq);
               txt_vale_utd1.setText(String.valueOf(valeutd));
               txt_eds1.setText(valeeds);
               txt_cg1.setText(String.valueOf(cant_gal));
               txt_precio1.setText(String.valueOf(valor_total));
               txt_km1.setText(String.valueOf(kilometraje));
               txta_obse3.setText(obse);
               
               
               JD_Mod.pack();
               JD_Mod.setLocationRelativeTo(null);
               JD_Mod.setVisible(true);
               JD_Mod.setResizable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
        
        
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarActionPerformed
         int opc=JOptionPane.showConfirmDialog(null,"Desea concluir el registro de consumo por estación?", "Aviso!", JOptionPane.YES_NO_OPTION); 
          
        if(opc==JOptionPane.YES_OPTION)
        {
            
        if(t_detalle.getRowCount()== 0 && t_detalle.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(null, "La tabla Detalle no contiene ningun registro!");
            
        }
        else 
        {
            
            try {
                //System.out.print(id_ctrl);

                totalizador();
            } catch (SQLException ex) {
                Logger.getLogger(JIFConsumoEstacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(null,"Se ha concluido con exito el registro de consumo por estación y la totalización del mismo");
            
            reporte=new ReporteConEstacion();
            
            reporte.ejecutarReporte2(idce);
          
           dispose();
           
        }
       } 
    }//GEN-LAST:event_btn_terminarActionPerformed

    private void cb_vehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vehiActionPerformed
          try {
           int idveh;
           Vehiculo v=(Vehiculo) cb_vehi.getSelectedItem();
           idveh=v.getId_vehiculo();
           System.out.println(idveh);
           
           cb_tc.removeAllItems();
          // cb_tc.removeAllItems();
           ResultSet obj=conexion.executeQuery("SELECT tc.name_combustible AS com,tca.name_combustible AS alterno FROM utilidades.vehiculos_equipos v JOIN utilidades.tipo_combustible tc ON tc.id_tipo_com=v.id_tipo_com JOIN utilidades.tipo_combustible tca ON tca.id_tipo_com=v.id_2tipo_com WHERE v.id_vehiculo="+idveh+" ");
           
           while (obj.next())
           {
              cb_tc.addItem(obj.getObject("com"));
              cb_tc.addItem(obj.getObject("alterno"));
             // cb_tc1.addItem(obj.getObject("com"));
              //cb_tc1.addItem(obj.getObject("alterno"));
             
          }
       } catch (SQLException ex) {
           Logger.getLogger(JIFControlCombustible.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_cb_vehiActionPerformed

    private void btn_agregarvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarvehiActionPerformed
        vehiculos=new JIFVehiculosEquipos();
        MDIPrincipal.escritorio.add(vehiculos);
        vehiculos.toFront();
        vehiculos.setVisible(true);
        
        btn_actualizar1.setEnabled(true);
    }//GEN-LAST:event_btn_agregarvehiActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        cb_vehi.removeAllItems();
        cb_vehi1.removeAllItems();
        cb_tc.removeAllItems();
        cb_tc1.removeAllItems();
        cargarItemVehiculo();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_agregarvehi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarvehi2ActionPerformed
        vehiculos=new JIFVehiculosEquipos();
        MDIPrincipal.escritorio.add(vehiculos);
        vehiculos.toFront();
        vehiculos.setVisible(true);
        
        btn_actualizar.setEnabled(true);
    }//GEN-LAST:event_btn_agregarvehi2ActionPerformed

    private void btn_actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar1ActionPerformed
         cb_vehi.removeAllItems();
        cb_vehi1.removeAllItems();
        cb_tc.removeAllItems();
        cb_tc1.removeAllItems();
        cargarItemVehiculo();
    }//GEN-LAST:event_btn_actualizar1ActionPerformed

    private void cb_vehi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vehi1ActionPerformed
         try {
           int idveh;
           Vehiculo v=(Vehiculo) cb_vehi.getSelectedItem();
           idveh=v.getId_vehiculo();
           
           //cb_tc.removeAllItems();
           cb_tc1.removeAllItems();
           ResultSet obj=conexion.executeQuery("SELECT tc.name_combustible AS com,tca.name_combustible AS alterno FROM utilidades.vehiculos_equipos v JOIN utilidades.tipo_combustible tc ON tc.id_tipo_com=v.id_tipo_com JOIN utilidades.tipo_combustible tca ON tca.id_tipo_com=v.id_2tipo_com WHERE v.id_vehiculo="+idveh+" ");
           
           while (obj.next())
           {
             // cb_tc.addItem(obj.getObject("com"));
             // cb_tc.addItem(obj.getObject("alterno"));
              cb_tc1.addItem(obj.getObject("com"));
             cb_tc1.addItem(obj.getObject("alterno"));
             
          }
       } catch (SQLException ex) {
           Logger.getLogger(JIFControlCombustible.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_cb_vehi1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Agregar;
    private javax.swing.JDialog JD_Mod;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_actualizar1;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregarvehi;
    private javax.swing.JButton btn_agregarvehi2;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelar1;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_terminar;
    private javax.swing.JComboBox cb_estacion;
    private javax.swing.JComboBox cb_tc;
    private javax.swing.JComboBox cb_tc1;
    private javax.swing.JComboBox cb_vehi;
    private javax.swing.JComboBox cb_vehi1;
    private com.toedter.calendar.JDateChooser dc_fechaTan;
    private com.toedter.calendar.JDateChooser dc_fechaTan1;
    private com.toedter.calendar.JDateChooser dc_fechaven;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel p_encabezado;
    private javax.swing.JTable t_detalle;
    private javax.swing.JTextField txt_cg;
    private javax.swing.JTextField txt_cg1;
    private javax.swing.JTextField txt_eds;
    private javax.swing.JTextField txt_eds1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_km;
    private javax.swing.JTextField txt_km1;
    private javax.swing.JTextField txt_numcta;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_precio1;
    private javax.swing.JTextField txt_vale_utd;
    private javax.swing.JTextField txt_vale_utd1;
    private javax.swing.JTextArea txta_obse;
    private javax.swing.JTextArea txta_obse2;
    private javax.swing.JTextArea txta_obse3;
    // End of variables declaration//GEN-END:variables
      public void cargarItemVehiculo()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemVehiculo();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_vehi.addItem(lista.get(i));
                cb_vehi1.addItem(lista.get(i));
            }
        }
    }
      
      public void bloquear()
     {
         txt_numcta.setEnabled(false);
         dc_fechaven.setEnabled(false);
         cb_estacion.setEnabled(false);
         txta_obse.setEnabled(false);
         
         btn_agregar.setEnabled(true);
         btn_eliminar.setEnabled(true);
         btn_mod.setEnabled(true);
         btn_terminar.setEnabled(true);
         
     }
      
     public void limpiar()
     {
         txt_vale_utd.setText("0");
         txt_eds.setText("000-000");
         dc_fechaTan.setDate(null);
         txt_cg.setText("0.00");
         txt_km.setText("0");
         txt_precio.setText("0");
         txta_obse2.setText("");
         
         txt_vale_utd1.setText("0");
         txt_eds1.setText("000-000");
         dc_fechaTan1.setDate(null);
         txt_cg1.setText("0.00");
         txt_km1.setText("0");
         txt_precio1.setText("0");
         txta_obse3.setText("");
     }

         public void LimpiarTabla()
    {
  
        for(int i=modelo.getRowCount()-1;i>=0;i--)
        {
            modelo.removeRow(i);
            
        }
    }
         
           
     public void eliminarRegistroTabla()
    {
         ConexionBD nueva=new ConexionBD();
        
        //Verifica que la fila de la tabla esta seleccionada
        if(t_detalle.isRowSelected(t_detalle.getSelectedRow()))
        {
           int row = t_detalle.getSelectedRow();

        for(int i = 0; i < modelo.getRowCount(); i++)
        {
           nueva.executeUpdateQuery("DELETE FROM consumo_combustible.det_con_eds WHERE id_det_ceds="+modelo.getValueAt(row,0)+" ");

        }
         int numRows = t_detalle.getSelectedRows().length;
         
         for(int i = 0; i < numRows ; i++ )
         {
            modelo.removeRow(row);
         } 
          
        }         
 
     else
     {
      JOptionPane.showMessageDialog(this, "Debe seleccionar un registro de la tabla para eliminarlo!."
         ,"Aviso", JOptionPane.WARNING_MESSAGE);
     }
          nueva.desconectar(); 
          LimpiarTabla();
          detalleTabla();  
    }
     
     
     public void detalleTabla()
        {
       try
        {
            ConexionBD nueva=new ConexionBD();
            

            
        ResultSet obj=nueva.executeQuery("SELECT d.id_det_ceds,d.fechatanq,(' Placa: ' || ve.placa_identi ||' - '||ma.descripcion ||' '|| li.descripcion)AS vehiculo, d.vale_utd,d.vale_eds,t.name_combustible,d.cant_gal,d.vlor_gal,d.valor_total,d.kilometraje,d.obse FROM consumo_combustible.det_con_eds d JOIN utilidades.tipo_combustible t ON t.id_tipo_com=d.id_tipo_com JOIN utilidades.vehiculos_equipos ve ON ve.id_vehiculo=d.id_vehiculo JOIN utilidades.linea_vehiculo li ON li.id_linea_vehi=ve.id_linea JOIN utilidades.marca_vehiculo ma ON ma.id_marca=li.id_marca WHERE d.id_ceds="+idce+" ORDER BY vehiculo ASC");
            
            
        while (obj.next()) 
        {
        
        Object [] datos = new Object[11];
        
     
        for (int i=0;i<11;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modelo.addRow(datos);
       
        }
           t_detalle.setModel(modelo);
            setCellRender(t_detalle);
           nueva.desconectar();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
       
       
   }
     
     public void totalizador() throws SQLException
     {
         //ConexionBD conexion=new ConexionBD();
         int total=0;
         int total_ccostos=0;
         String centro="";
         
         ResultSet obj=conexion.executeQuery("SELECT SUM(valor_total) AS total FROM consumo_combustible.det_con_eds WHERE id_ceds="+idce+"");
         
         while (obj.next())
         {
             total=obj.getInt("total");
         }
         
         conexion.executeUpdateQuery("UPDATE consumo_combustible.consumo_estacion SET total_pesos="+total+" WHERE id_ce="+idce+"");
         
         ResultSet obj1=conexion.executeQuery("SELECT (c.nombre_centro_costos ||' - '|| i.nombre_item_ccostos) AS centro, SUM (eds.valor_total)AS total FROM consumo_combustible.det_con_eds eds JOIN utilidades.vehiculos_equipos v ON v.id_vehiculo=eds.id_vehiculo JOIN utilidades.itemccostos i ON i.id_item_ccostos=v.id_item_ccostos JOIN utilidades.centrocostos c ON i.id_centrocostos=c.id_centrocostos WHERE eds.id_ceds="+idce+" GROUP BY centro");
         
         while (obj1.next())
         {
             centro=obj1.getString("centro");
             total_ccostos=obj1.getInt("total");
             conexion.executeUpdateQuery("INSERT INTO consumo_combustible.total_ccostos_ce (nom_ccosto,total_ccosto,id_ce)VALUES('"+centro+"', "+total_ccostos+", "+idce+")");        

         }
         
         conexion.desconectar();
     }
     
          public void setCellRender(JTable table) {
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
        }
    }

}
