/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syscv.utd.presentacion;

import com.syscv.utd.conexionBD.ConexionBD;
import com.syscv.utd.dao.ctrlcom.documentos.ManejoImagen;
import com.syscv.utd.entidades.ControllerItemList;
import com.syscv.utd.entidades.FormaPago;
import com.syscv.utd.recursos.JPColor;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jonathan
 */
public class JIFPagoComparendo extends javax.swing.JInternalFrame {

    private ConexionBD conexion=new ConexionBD();
   

    private int id_usuario=MDIPrincipal.getvSeccion();
    private int id_comparendo=0;
    private int id_formapago=0;
    private ManejoImagen mi=new ManejoImagen();
    
    private DefaultTableModel modelo;
    
    private TableRowSorter trsFiltro;
   

    
    
    
    
    public JIFPagoComparendo() {
        
     
        initComponents();
        
        conexion=new ConexionBD();
        
        this.dc_fecha.setDate(new Date());

        
        Color c1=new Color(66,111,166);
        Color c2=new Color(102,174,118);
        JPColor miColor=new JPColor(c1,c2);
        miColor.setSize(this.getSize());
        p_encabezado.add(miColor);
        
     
        
        modelo=new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Placa");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("C.C Conductor");
        modelo.addColumn("Conductor");
        modelo.addColumn("N° Comparendo");
        modelo.addColumn("Fecha Comparendo");
        modelo.addColumn("Valor");
        modelo.addColumn("Estado Comparendo");
        
        setCellRender(tb_consulta);
        

        try {
            consultar();
            cargarFormaPago();
            
            
            

//            }  
        } catch (SQLException ex) {
            Logger.getLogger(JIFPagoComparendo.class.getName()).log(Level.SEVERE, null, ex);
        }
               
               
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        JD_Comparendo = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        btn_sel = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_consulta = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        txt_filtro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cb_filtro = new javax.swing.JComboBox();
        p_encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tp_general = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_cancelar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        txt_comparendo = new javax.swing.JTextField();
        btn_comprobar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        txt_vlor_pagar = new javax.swing.JTextField();
        cb_pago = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_paz_salvo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel6.setText("jLabel6");

        jLabel11.setText("jLabel11");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton2");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Comparendos"));

        btn_sel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/add.png"))); // NOI18N
        btn_sel.setToolTipText("Seleccionar Fila");
        btn_sel.setBorderPainted(false);
        btn_sel.setContentAreaFilled(false);
        btn_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selActionPerformed(evt);
            }
        });

        tb_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tb_consulta);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btn_sel)
                .addGap(0, 306, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));

        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filtroKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Buscar Por");

        cb_filtro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Placa", "Vehiculo", "Conductor", "N° Comparendo" }));
        cb_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filtroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(cb_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cb_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout JD_ComparendoLayout = new javax.swing.GroupLayout(JD_Comparendo.getContentPane());
        JD_Comparendo.getContentPane().setLayout(JD_ComparendoLayout);
        JD_ComparendoLayout.setHorizontalGroup(
            JD_ComparendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ComparendoLayout.setVerticalGroup(
            JD_ComparendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_ComparendoLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Reg. Pago Comparendos --UTDVVCC--");

        p_encabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Registro Pago Comparendo");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/pagos_2.png"))); // NOI18N

        javax.swing.GroupLayout p_encabezadoLayout = new javax.swing.GroupLayout(p_encabezado);
        p_encabezado.setLayout(p_encabezadoLayout);
        p_encabezadoLayout.setHorizontalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
        );
        p_encabezadoLayout.setVerticalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addGroup(p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_encabezadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_encabezadoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("ID Comparendo *");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Descripción *");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_cancelar1.setText("Cancelar");
        txt_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cancelar1ActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        txt_comparendo.setEditable(false);
        txt_comparendo.setText("0");

        btn_comprobar.setText("Comprobar");
        btn_comprobar.setToolTipText("Seleccionar el Comparendo a pagar");
        btn_comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprobarActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Fecha Pago *");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Valor a Pagar $ *");

        txt_vlor_pagar.setEditable(false);
        txt_vlor_pagar.setText("0");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Forma de Pago *");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setText("Paz y Salvo N° *");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Campos Obligatorios *");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cancelar1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_comparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_comprobar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_paz_salvo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29)))
                                .addGap(18, 18, 18)
                                .addComponent(txt_vlor_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(cb_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_comparendo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_comprobar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txt_vlor_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_paz_salvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(txt_cancelar1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tp_general.addTab("Pago Comparendo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tp_general)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_general))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cancelar1ActionPerformed
       
        int opc=JOptionPane.showConfirmDialog(null,"Desea concluir el registro del Pago del comparendo ?", "Aviso!", JOptionPane.YES_NO_OPTION); 
          
        if(opc==JOptionPane.YES_OPTION)
        {
              this.dispose();
        }
      
      
        
        
    }//GEN-LAST:event_txt_cancelar1ActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try
        {

          int opc=JOptionPane.showConfirmDialog(null,"Desea guardar el pago del comparendo ?", "Aviso!", JOptionPane.YES_NO_OPTION); 
   
           if(opc==JOptionPane.YES_OPTION)
        {
             
     
            
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter( new FileNameExtensionFilter("Archivo de Imagen","jpg") );
        fileChooser.setCurrentDirectory(new java.io.File("e:/imagenes_tmp/"));
        int result = fileChooser.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ){
            //obtiene ruta y nombre del archivo
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            String name = fileChooser.getSelectedFile().getName();
            
            FormaPago f=(FormaPago) cb_pago.getSelectedItem();
            id_formapago=f.getId_formaPago(); 
           
           
            
            Date fecha=dc_fecha.getDate();           
            java.sql.Date sqlFecha_fact = new java.sql.Date(fecha.getTime());
            id_comparendo= Integer.parseInt(txt_comparendo.getText());
            int vlorpagar=Integer.parseInt(txt_vlor_pagar.getText());
            String paz_salvo=txt_paz_salvo.getText();
            String des=txt_area.getText();
            
            
            if(id_comparendo==0|| vlorpagar==0 || id_formapago==0 ||paz_salvo.equals("") || des.equals(""))
            {
                throw new Exception("Campos Obligatorios.");
            }
            
              
                            
                if( mi.guardarPagos(GenerarCodigo() , name, ruta, id_comparendo, sqlFecha_fact,vlorpagar,des,paz_salvo,id_formapago,id_usuario) )
                {
                    JOptionPane.showMessageDialog(this,"Documento ["+name+"] almacenado");
                    JOptionPane.showMessageDialog(null, "Se guardó con exito el Pago del Comparendo");
      
                    conexion.executeUpdateQuery("UPDATE utilidades.comparendos SET estado=true WHERE id_comparendo="+id_comparendo+"");
                    conexion.desconectar();
                    limpiar();
                    
                    
  
                }
        }
      } 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selActionPerformed

        

        if(tb_consulta.isRowSelected(tb_consulta.getSelectedRow()))
        {

            id_comparendo=(int) tb_consulta.getValueAt(tb_consulta.getSelectedRow(), 0);
            int valor=(int )tb_consulta.getValueAt(tb_consulta.getSelectedRow(), 7);
            txt_comparendo.setText(String.valueOf(id_comparendo));
            txt_vlor_pagar.setText(String.valueOf(valor));
           

            JD_Comparendo.dispose();

        }else
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_selActionPerformed

    private void txt_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyTyped
        txt_filtro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txt_filtro.getText());
                txt_filtro.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tb_consulta.getModel());
        tb_consulta.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txt_filtroKeyTyped

    private void cb_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_filtroActionPerformed

    private void btn_comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprobarActionPerformed
         JD_Comparendo.pack();
         JD_Comparendo.setLocationRelativeTo(null);
         JD_Comparendo.setVisible(true);
         JD_Comparendo.setResizable(false);
    }//GEN-LAST:event_btn_comprobarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Comparendo;
    private javax.swing.JButton btn_comprobar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_sel;
    private javax.swing.JComboBox cb_filtro;
    private javax.swing.JComboBox cb_pago;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel p_encabezado;
    private javax.swing.JTable tb_consulta;
    private javax.swing.JTabbedPane tp_general;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JButton txt_cancelar1;
    private javax.swing.JTextField txt_comparendo;
    private javax.swing.JTextField txt_filtro;
    private javax.swing.JTextField txt_paz_salvo;
    private javax.swing.JTextField txt_vlor_pagar;
    // End of variables declaration//GEN-END:variables

     

      //Genera un código unico para la imagen
    private String GenerarCodigo()
    {
        SimpleDateFormat sdf= new SimpleDateFormat("hhmmss");
        return sdf.format(new Date());
    }
    
         public void cargarFormaPago()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarFormaPago();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_pago.addItem(lista.get(i));
              
              
            }
        }
    }    

         public void limpiar()
         {
             txt_comparendo.setText("0");
             txt_vlor_pagar.setText("0");
             txt_paz_salvo.setText("");
             txt_area.setText("");
         
         }
         
         
         
     public void consultar() throws SQLException
{
  try
        {
        
        conexion=new ConexionBD();
        
        
        ResultSet obj=conexion.executeQuery("SELECT com.id_comparendo,ve.placa_identi, (ma.descripcion ||' '||li.descripcion)AS linea_marca, con.cedula, (con.nombre ||' '||con.apellido)AS conductor, com.num_comparendo, com.fecha_comparendo,com.valor,CASE WHEN com.estado='false' THEN 'No cancelado' ELSE 'Cancelado' END AS estado  "
                + " FROM utilidades.comparendos com JOIN utilidades.vehiculos_equipos ve "
                + " ON ve.id_vehiculo=com.id_vehiculo "
                + " JOIN utilidades.linea_vehiculo li ON li.id_linea_vehi=ve.id_linea "
                + " JOIN utilidades.marca_vehiculo ma ON ma.id_marca=li.id_marca "
                + " JOIN utilidades.conductor con ON con.id_conductor=com.id_conductor "
                + " WHERE  com.estado='false' "
                + "ORDER BY com.id_comparendo DESC");
        
         while (obj.next()) 
        {
        
        Object [] datos = new Object[9];
        
     
        for (int i=0;i<9;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modelo.addRow(datos);
       
        }
           tb_consulta.setModel(modelo);
           
        TableColumnModel columnModel =tb_consulta.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(20);
        columnModel.getColumn(2).setPreferredWidth(50);
        columnModel.getColumn(3).setPreferredWidth(20);
        columnModel.getColumn(4).setPreferredWidth(50);
         columnModel.getColumn(5).setPreferredWidth(30);
         columnModel.getColumn(6).setPreferredWidth(30);
          columnModel.getColumn(7).setPreferredWidth(30);
           columnModel.getColumn(8).setPreferredWidth(30);
      
      
        
        
        
          setCellRender(tb_consulta);
          conexion.desconectar();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
}    
     
        // color a la tabla
   public void setCellRender(JTable table) {
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
        }
    }

     public void filtro() {
        int columnaABuscar = 0;
       
        if (cb_filtro.getSelectedItem() == "ID") {
            columnaABuscar = 0;
        }
        
           if (cb_filtro.getSelectedItem() == "Placa") {
            columnaABuscar = 1;
        }
           if (cb_filtro.getSelectedItem() == "Vehiculo") {
            columnaABuscar = 2;
        }
           
            if (cb_filtro.getSelectedItem() == "Conductor") {
            columnaABuscar = 4;
        }
            
              if (cb_filtro.getSelectedItem() == "N° Comparendo") {
            columnaABuscar = 5;
        }
        
       
        
        
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt_filtro.getText(), columnaABuscar));

    }
}
