/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syscv.utd.presentacion;

import com.syscv.utd.DaoMtos.Dao_Dt_Mto_Interno;
import com.syscv.utd.DaoMtos.Dao_Mto_Interno;
import com.syscv.utd.conexionBD.ConexionBD;
import com.syscv.utd.conexionBD.ConexionBDM;
import com.syscv.utd.entidades.ControllerItemList;
import com.syscv.utd.entidades.Detalle_Mto_Interno;
import com.syscv.utd.entidades.Mantenimiento_Interno;
import com.syscv.utd.entidades.Mecanico_UTD;
import com.syscv.utd.entidades.Rutina_mto;
import com.syscv.utd.entidades.Servicio_mec_interno;
import com.syscv.utd.entidades.Tipo_Mto;
import com.syscv.utd.entidades.Vehiculo;
import com.syscv.utd.recursos.JPColor;
import com.syscv.utd.reportes.ReporteTallerInterno;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jonathan
 */
public class JIFTallerInterno extends javax.swing.JInternalFrame {

    ConexionBD conexion=new ConexionBD();
    private Mantenimiento_Interno mto;
    private Detalle_Mto_Interno dt_mto;
    private ReporteTallerInterno reporte;
    
    private Dao_Mto_Interno mtoInterno;
    private Dao_Dt_Mto_Interno daodt;
    private Servicio_mec_interno s;
    private int id_tabla;
    int id_vehiculo, consecutivo, idmtointerno, id_servicio_mec;
    
    private DefaultTableModel modelo;
    
    private boolean verificar;
    
    
    SimpleDateFormat df = new SimpleDateFormat("hh:mm a");
    
    public JIFTallerInterno() throws SQLException {
        initComponents();
        
         Color c1=new Color(66,111,166);
        Color c2=new Color(102,174,118);
        JPColor miColor=new JPColor(c1,c2);
        miColor.setSize(this.getSize());
        p_encabezado.add(miColor);
        
        cargarItemVehiculo();
        cargarItemTipoMto();
        cargarItemRutina();
        cargarItemMecanico();
        
        
         modelo=new DefaultTableModel();
     
        modelo.addColumn("ID");
        modelo.addColumn("Servicio Interno");
        modelo.addColumn("Novedades");
        modelo.addColumn("REQ. Mto. Externo");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Detalle = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area_nov = new javax.swing.JTextArea();
        btn_guardar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_servicio = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cb_mto_externo = new javax.swing.JCheckBox();
        JD_Detalle_Mod = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_area_nov1 = new javax.swing.JTextArea();
        btn_guardar1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cb_servicio1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cb_mto_externo1 = new javax.swing.JCheckBox();
        p_encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tc_salida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_id_mto = new javax.swing.JTextField();
        dc_fecha_llegada = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cb_vehiculo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txt_km_llegada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_horas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_prox_mto = new javax.swing.JTextField();
        cb_rutina = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cb_mecanico = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txt_rem_almacen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dc_salida = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        t_salida = new org.bolivia.time.TimeChooser();
        tc_llegada = new org.bolivia.time.TimeChooser();
        btn_guardar_en = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_consecutivo = new javax.swing.JTextField();
        cbx_requiere = new javax.swing.JCheckBox();
        btn_verificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_detalle = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();

        JD_Detalle.setTitle("Detalle Mantenimiento");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Novedades");

        txt_area_nov.setColumns(20);
        txt_area_nov.setRows(5);
        jScrollPane3.setViewportView(txt_area_nov);

        btn_guardar.setText("Aceptar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(153, 0, 0));
        jLabel19.setText("* Campos Obligatorios");

        jLabel22.setText("Servicio Mecánico *");

        cb_servicio.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel26.setText("Req. Mto. Externo");

        cb_mto_externo.setText("Mto. Externo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(cb_mto_externo))
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_servicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cb_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cb_mto_externo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_DetalleLayout = new javax.swing.GroupLayout(JD_Detalle.getContentPane());
        JD_Detalle.getContentPane().setLayout(JD_DetalleLayout);
        JD_DetalleLayout.setHorizontalGroup(
            JD_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_DetalleLayout.setVerticalGroup(
            JD_DetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JD_Detalle_Mod.setTitle("Modificar Detalle");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Novedades");

        txt_area_nov1.setColumns(20);
        txt_area_nov1.setRows(5);
        jScrollPane5.setViewportView(txt_area_nov1);

        btn_guardar1.setText("Aceptar");
        btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar1ActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(153, 0, 0));
        jLabel24.setText("* Campos Obligatorios");

        jLabel25.setText("Servicio Mecánico *");

        cb_servicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_servicio1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Req. Mto Externo");

        cb_mto_externo1.setText("Mto. Externo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cb_mto_externo1))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_guardar1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25)
                                .addComponent(jLabel23))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5)
                                .addComponent(cb_servicio1, 0, 404, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cb_servicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_mto_externo1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar1)
                            .addComponent(jButton2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout JD_Detalle_ModLayout = new javax.swing.GroupLayout(JD_Detalle_Mod.getContentPane());
        JD_Detalle_Mod.getContentPane().setLayout(JD_Detalle_ModLayout);
        JD_Detalle_ModLayout.setHorizontalGroup(
            JD_Detalle_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_Detalle_ModLayout.setVerticalGroup(
            JD_Detalle_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Mantenimientos Internos Mecánica --UTDVVCC--");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("MANTENIMIENTO TALLER INTERNO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/taller_int.png"))); // NOI18N

        javax.swing.GroupLayout p_encabezadoLayout = new javax.swing.GroupLayout(p_encabezado);
        p_encabezado.setLayout(p_encabezadoLayout);
        p_encabezadoLayout.setHorizontalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(273, 273, 273))
        );
        p_encabezadoLayout.setVerticalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tc_salida.setBorder(javax.swing.BorderFactory.createTitledBorder("Mto. Taller Interno"));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("ID MTO. INT.");

        txt_id_mto.setEditable(false);
        txt_id_mto.setBackground(new java.awt.Color(255, 255, 0));
        txt_id_mto.setForeground(new java.awt.Color(102, 102, 0));
        txt_id_mto.setText("0");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Vehiculo / Equipo *");

        cb_vehiculo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vehiculoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Km de llegada *");

        txt_km_llegada.setText("0");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Horas de Uso *");

        txt_horas.setText("0");
        txt_horas.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Rutina *");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Km proximo Mto. *");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Tipo de Mto. *");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Mecánico Asignado *");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("REM-ALMACEN  * ");

        txt_rem_almacen.setText("0");

        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setText("* Campos Obligatorios");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Fecha de llegada *");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Hora de Llegada *");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Fecha de Salida *");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Hora de salida *");

        t_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_salidaActionPerformed(evt);
            }
        });

        btn_guardar_en.setText("Guardar");
        btn_guardar_en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_enActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Consecutivo Equipo/Vehiculo");

        txt_consecutivo.setEditable(false);
        txt_consecutivo.setBackground(new java.awt.Color(255, 255, 0));

        cbx_requiere.setText("Requiere Mto. Externo.");

        btn_verificar.setText("Verificar");
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tc_salidaLayout = new javax.swing.GroupLayout(tc_salida);
        tc_salida.setLayout(tc_salidaLayout);
        tc_salidaLayout.setHorizontalGroup(
            tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tc_salidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_consecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tc_salidaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tc_salidaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dc_fecha_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(10, 10, 10)
                        .addComponent(tc_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(dc_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tc_salidaLayout.createSequentialGroup()
                        .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tc_salidaLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(24, 24, 24)
                                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel11)))
                            .addGroup(tc_salidaLayout.createSequentialGroup()
                                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)
                                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tc_salidaLayout.createSequentialGroup()
                                        .addComponent(txt_id_mto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16))
                                    .addComponent(cb_rutina, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tc_salidaLayout.createSequentialGroup()
                                        .addComponent(txt_km_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tc_salidaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_prox_mto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tc_salidaLayout.createSequentialGroup()
                                .addComponent(cb_mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_rem_almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_verificar)))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(tc_salidaLayout.createSequentialGroup()
                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tc_salidaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar_en))
                    .addGroup(tc_salidaLayout.createSequentialGroup()
                        .addComponent(cbx_requiere)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tc_salidaLayout.setVerticalGroup(
            tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tc_salidaLayout.createSequentialGroup()
                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_id_mto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_consecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_rutina, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_km_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txt_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txt_prox_mto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tc_salidaLayout.createSequentialGroup()
                        .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(cb_mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dc_fecha_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20)
                                .addComponent(tc_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(t_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dc_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx_requiere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(btn_guardar_en)))
                    .addGroup(tc_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_rem_almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_verificar)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tb_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_detalle);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/add.png"))); // NOI18N
        btn_agregar.setToolTipText("Adicionar Linea");
        btn_agregar.setBorderPainted(false);
        btn_agregar.setContentAreaFilled(false);
        btn_agregar.setEnabled(false);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/delete.png"))); // NOI18N
        btn_eliminar.setToolTipText("Eliminar Linea");
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/mod_detalle.png"))); // NOI18N
        btn_mod.setToolTipText("Modificar Linea");
        btn_mod.setBorderPainted(false);
        btn_mod.setContentAreaFilled(false);
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btn_mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar)))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tc_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_imprimir)
                .addGap(5, 5, 5)
                .addComponent(btn_cancelar)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tc_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_imprimir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        
                
       
                 JD_Detalle.pack();
                 JD_Detalle.setLocationRelativeTo(null);
                 JD_Detalle.setVisible(true);
                 JD_Detalle.setResizable(false);
               
            
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
         
        String  novedad;
        
        
        if(tb_detalle.isRowSelected(tb_detalle.getSelectedRow()))
            {
                
        id_tabla = (Integer) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 0);    

        novedad=(String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 3);
                
        
        txt_area_nov1.setText(novedad);
                
                 JD_Detalle_Mod.pack();
                 JD_Detalle_Mod.setLocationRelativeTo(null);
                 JD_Detalle_Mod.setVisible(true);
                 JD_Detalle_Mod.setResizable(false);
     
            }else
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_modActionPerformed

    private void t_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_salidaActionPerformed

    private void btn_guardar_enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_enActionPerformed
       
         try
         {
            int id_rutina=0;
            int id_tipo_mto=0;
            int id_mecanico=0;
            int id_usuario=0;
         
            Date fecha_llegada, fecha_salida;
            
            
            mto=new Mantenimiento_Interno();
            mtoInterno=new Dao_Mto_Interno();
            
            fecha_llegada=dc_fecha_llegada.getDate();
            fecha_salida=dc_salida.getDate();
            
            
           if(Integer.parseInt(txt_km_llegada.getText()) >= Integer.parseInt(txt_prox_mto.getText()))
           {
               throw new Exception("El Km de llegada no debe ser igual o mayor al km del proximo Mantenimiento.");
           }
           
           if(fecha_salida.before(fecha_llegada))
           {
             throw new Exception("La Fecha de Salida no puede ser inferior a la fecha de Entrada ");

           }
           
           if(horasSalida().before(horasllegada()))
           {
              throw new Exception("La Hora de salida no puede ser menor que la Hora de entrada");

           }
            
            Rutina_mto r=(Rutina_mto) cb_rutina.getSelectedItem();
            id_rutina=r.getRutina();
            
            Tipo_Mto t=(Tipo_Mto) cb_tipo.getSelectedItem();
            id_tipo_mto=t.getId();
            
            Mecanico_UTD m=(Mecanico_UTD) cb_mecanico.getSelectedItem();
            id_mecanico=m.getId_meca();
            
            id_usuario=MDIPrincipal.getvSeccion();
            
            mto.setKm_llegada(Integer.parseInt(txt_km_llegada.getText()));
            mto.setHoras_uso(Integer.parseInt(txt_horas.getText()));
            mto.setKm_prox_mto(Integer.parseInt(txt_prox_mto.getText()));
            mto.setId_vehiculo(id_vehiculo);
            mto.setId_rutina(id_rutina);
            mto.setId_t_mto(id_tipo_mto);
            mto.setId_mecanico(id_mecanico);
            
            mto.setHora_entrada(horasllegada());
            mto.setHora_salida(horasSalida());
            mto.setConsecutivo_vehiculo(consecutivo);
            
            mto.setFecha_entrada(fecha_llegada);
            mto.setFecha_salida(fecha_salida);
            mto.setId_usuario(id_usuario);
            mto.setFecha_reg(new Date());
            
            
            
            if(verificar==true)
            {
               mto.setSalida_almacen(Integer.parseInt(txt_rem_almacen.getText()));

            }
            else
            {
                throw new Exception("Verifique la Salida de Almacen correspondiente a este Mto.");
            }
            
            if(cbx_requiere.isSelected())
            {
                mto.setMto_externo(true);
            }
            else
                {
                    mto.setMto_externo(false);
                }
          
            
            
            
            mtoInterno.guardar(mto);
            idmtointerno= Dao_Mto_Interno.getIdMtoInterno();
            txt_id_mto.setText(String.valueOf(idmtointerno));
            conexion.executeUpdateQuery("UPDATE utilidades.vehiculos_equipos SET consecutivo_mto_interno="+txt_consecutivo.getText()+" WHERE id_vehiculo="+id_vehiculo+"");

            btn_guardar_en.setEnabled(false);
            cb_vehiculo.setEditable(false);
            
             cargarItemServicio(mto.getId_rutina());
             
             btn_agregar.setEnabled(true);
            
            
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error " + ex);
        }
         
        
         
        
        
        
    }//GEN-LAST:event_btn_guardar_enActionPerformed

    private void cb_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vehiculoActionPerformed
        try {
            Vehiculo v=(Vehiculo) cb_vehiculo.getSelectedItem();
            id_vehiculo=v.getId_vehiculo();
            

            ResultSet obj=conexion.executeQuery("SELECT consecutivo_mto_interno+1 AS consecutivo FROM utilidades.vehiculos_equipos WHERE id_vehiculo="+id_vehiculo+" ");
            
            if(obj.next())
            {
                consecutivo=obj.getInt("consecutivo");
                
                txt_consecutivo.setText(String.valueOf(consecutivo));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JIFTallerInterno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_vehiculoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        try {
            s=new Servicio_mec_interno();
            dt_mto=new Detalle_Mto_Interno();
            daodt=new Dao_Dt_Mto_Interno();
            
            int id_servicio=0;
           
             if(cb_mto_externo.isSelected()==true)
            {
                dt_mto.setMto_externo(true);
            }if(cb_mto_externo.isSelected()==false)
            {
                dt_mto.setMto_externo(false);
            }
         
                 
            
            dt_mto.setId_mto_interno(idmtointerno);
            dt_mto.setNovedades(txt_area_nov.getText());
            
            Servicio_mec_interno ser=(Servicio_mec_interno) cb_servicio.getSelectedItem();
            id_servicio=ser.getId_servicio();
            dt_mto.setId_servicio(id_servicio);
            
            daodt.guardar(dt_mto);
            
            LimpiarTabla();
            detalleTabla();
            
            
            txt_area_nov.setText("");
    
            
            btn_mod.setEnabled(true);
            btn_eliminar.setEnabled(true);
            
            JOptionPane.showMessageDialog(rootPane, "Se registro con exito el item");
            
            JD_Detalle_Mod.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
           
        
        
        
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar1ActionPerformed
         try {
            s=new Servicio_mec_interno();
            dt_mto=new Detalle_Mto_Interno();
            daodt=new Dao_Dt_Mto_Interno();
            
            int id_servicio=0;
           
             if(cb_mto_externo1.isSelected()==true)
            {
                dt_mto.setMto_externo(true);
            }if(cb_mto_externo1.isSelected()==false)
            {
                dt_mto.setMto_externo(false);
            }

            dt_mto.setId_mto_interno(idmtointerno);
            dt_mto.setNovedades(txt_area_nov1.getText());
            
            Servicio_mec_interno ser=(Servicio_mec_interno) cb_servicio1.getSelectedItem();
            id_servicio=ser.getId_servicio();
            dt_mto.setId_servicio(id_servicio);
            
            daodt.actualizar(dt_mto, id_tabla);
            
            LimpiarTabla();
            detalleTabla();
            
            txt_area_nov1.setText("");
    
         
            
            JOptionPane.showMessageDialog(rootPane, "Se actualizo con exito el item");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btn_guardar1ActionPerformed

    private void cb_servicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_servicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_servicio1ActionPerformed

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
        int rem=Integer.parseInt(txt_rem_almacen.getText());
   
        consultarSalidas(rem);
    }//GEN-LAST:event_btn_verificarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
  
  try {
        
        int opc=JOptionPane.showConfirmDialog(null,"Desea concluir El Reg. Mto. Taller Interno?", "Aviso!", JOptionPane.YES_NO_OPTION); 

        
        if(opc==JOptionPane.YES_OPTION)
        {
    
            
        if(tb_detalle.getRowCount()== 0 && tb_detalle.getSelectedRow()==-1)
        {
         
           throw new Exception("La Tabla detalle no tiene ningún item adicionado!");

        }
        
        reporte=new ReporteTallerInterno();
        
        reporte.ejecutarReporte(Integer.parseInt(txt_id_mto.getText()));
        
        this.dispose();
      }

      } catch (Exception ex) 
       {
          JOptionPane.showMessageDialog(rootPane, ex);
       }  
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        int opc=JOptionPane.showConfirmDialog(null,"Desea concluir El Reg. Mto. Taller Interno?", "Aviso!", JOptionPane.YES_NO_OPTION); 

        
        if(opc==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
        daodt=new Dao_Dt_Mto_Interno();
        
        if(tb_detalle.isRowSelected(tb_detalle.getSelectedRow()))
            {
                
                id_tabla = (Integer) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 0);
                
               daodt.eliminar(id_tabla);
               
               LimpiarTabla();
                
               detalleTabla();
               
               JOptionPane.showMessageDialog(rootPane, "Se eliminó con exito el item");
                
            }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JD_Detalle.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JD_Detalle_Mod.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        reporte=new ReporteTallerInterno();
        
        reporte.ejecutarReporte(Integer.parseInt(txt_id_mto.getText()));
        
    }//GEN-LAST:event_btn_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Detalle;
    private javax.swing.JDialog JD_Detalle_Mod;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JButton btn_guardar_en;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_verificar;
    private javax.swing.JComboBox cb_mecanico;
    private javax.swing.JCheckBox cb_mto_externo;
    private javax.swing.JCheckBox cb_mto_externo1;
    private javax.swing.JComboBox cb_rutina;
    private javax.swing.JComboBox cb_servicio;
    private javax.swing.JComboBox cb_servicio1;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JComboBox cb_vehiculo;
    private javax.swing.JCheckBox cbx_requiere;
    private com.toedter.calendar.JDateChooser dc_fecha_llegada;
    private com.toedter.calendar.JDateChooser dc_salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel p_encabezado;
    private org.bolivia.time.TimeChooser t_salida;
    private javax.swing.JTable tb_detalle;
    private org.bolivia.time.TimeChooser tc_llegada;
    private javax.swing.JPanel tc_salida;
    private javax.swing.JTextArea txt_area_nov;
    private javax.swing.JTextArea txt_area_nov1;
    private javax.swing.JTextField txt_consecutivo;
    private javax.swing.JTextField txt_horas;
    private javax.swing.JTextField txt_id_mto;
    private javax.swing.JTextField txt_km_llegada;
    private javax.swing.JTextField txt_prox_mto;
    private javax.swing.JTextField txt_rem_almacen;
    // End of variables declaration//GEN-END:variables
       public void cargarItemVehiculo()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemVehiculo();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_vehiculo.addItem(lista.get(i));
            }
        }
    }
       
       public void cargarItemTipoMto()
       {
           ControllerItemList control=new ControllerItemList();
           ArrayList lista=control.listarItemTipoMto();
           
           if(lista !=null)
           {
               int size=lista.size();
               for(int i=0; i<size; i++)
            {
                cb_tipo.addItem(lista.get(i));
            }
           }
           
           
       }
       
          public void cargarItemRutina()
       {
           ControllerItemList control=new ControllerItemList();
           ArrayList lista=control.listarItemRutina();
           
           if(lista !=null)
           {
               int size=lista.size();
               for(int i=0; i<size; i++)
            {
                cb_rutina.addItem(lista.get(i));
            }
           }
           
           
       }
       
        public void cargarItemMecanico()
       {
           ControllerItemList control=new ControllerItemList();
           ArrayList lista=control.listarItemMecanico();
           
           if(lista !=null)
           {
               int size=lista.size();
               for(int i=0; i<size; i++)
            {
                cb_mecanico.addItem(lista.get(i));
            }
           }
           
           
       }
        
          public void cargarItemServicio(int mto)
       {
           ControllerItemList control=new ControllerItemList();
           ArrayList lista=control.listarItemServicioMec(mto);
           
           if(lista !=null)
           {
               int size=lista.size();
               for(int i=0; i<size; i++)
            {
                cb_servicio.addItem(lista.get(i));
                cb_servicio1.addItem(lista.get(i));
            }
           }
           
           
       }

       public Time horasllegada()
       {
           long ms=0;
           
           String hora_llegada=(tc_llegada.getText());
            
            
            
        try {
            ms= df.parse(hora_llegada).getTime();
        } catch (ParseException ex) {
            Logger.getLogger(JIFTallerInterno.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
            Time t = new Time(ms);
            
            return t;
       }
       
         public Time horasSalida()
       {
           long ms=0;
           
           String hora_llegada=(t_salida.getText());
            
            
            
        try {
            ms= df.parse(hora_llegada).getTime();
        } catch (ParseException ex) {
            Logger.getLogger(JIFTallerInterno.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
            Time t = new Time(ms);
            
            return t;
       }

         
   
         
      // Metodo para llenar la tabla detalle
       public void detalleTabla()
        {
       try
        {
            ConexionBD nueva=new ConexionBD();
            
            ResultSet obj=nueva.executeQuery("SELECT d.id_dt_mto_interno,l.labor,d.novedades, d.mto_externo FROM mantenimientos_mecanica.mto_internos m JOIN mantenimientos_mecanica.dt_mto_interno d ON m.id_mto_interno=d.id_mto_interno JOIN utilidades.labor_mecanico l ON l.id_labor=d.id_labor_mec WHERE d.id_mto_interno="+idmtointerno+" AND anulado=false");
            
            
            
            while (obj.next()) 
        {
        
        Object [] datos = new Object[4];
        
     
        for (int i=0;i<4;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modelo.addRow(datos);
       
        }
           tb_detalle.setModel(modelo);
            setCellRender(tb_detalle);
           nueva.desconectar();
       

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }



        }
       
       
        public void setCellRender(JTable table) {
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
        }
      }
        
        
        
        public void consultarSalidas(int rem)
        {
             try
        {
            ConexionBDM nueva=new ConexionBDM();
            
            String cadena;
            
            ResultSet obj=nueva.executeQuery("SELECT h.id_hoja_mto,h.fecha_mto, v.placa_equipo FROM hoja_mantenimiento h JOIN vehiculos_equipos v ON v.id_vehiculo=h.vehiculos_equipos_id_vehiculo WHERE id_hoja_mto="+rem+" ");
            
            
            
        if (obj.next()==true) 
        {
        
        
            cadena="REM N° " + obj.getInt("h.id_hoja_mto") + " Fecha " + obj.getDate("h.fecha_mto") + " PLACA " + obj.getString("v.placa_equipo");
            
            JOptionPane.showMessageDialog(rootPane, "La Salida de Almacen se encontro en el sistema " + cadena);
            
            verificar=true;
       
        }
        else
        {
           JOptionPane.showMessageDialog(rootPane, "La Salida no se encontro en el sistema de almacén");
           verificar=false;
        }
         
           nueva.desconectar();
       

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }


            
        }
        
        
          public void LimpiarTabla()
    {
  
        for(int i=modelo.getRowCount()-1;i>=0;i--)
        {
            modelo.removeRow(i);
            
        }
    }

}
