/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syscv.utd.presentacion;

import com.syscv.utd.DaoMtos.Dao_Dtlle_mto_externo;
import com.syscv.utd.DaoMtos.Dao_mto_ext;
import com.syscv.utd.conexionBD.ConexionBD;
import com.syscv.utd.entidades.ControllerItemList;
import com.syscv.utd.entidades.Dtalle_mto_externo;
import com.syscv.utd.entidades.ItemSistema;
import com.syscv.utd.entidades.Mantenimientos_Externos;
import com.syscv.utd.entidades.Sistemas;
import com.syscv.utd.entidades.TallerExterno;
import com.syscv.utd.entidades.Tipo_Mto;
import com.syscv.utd.entidades.Vehiculo;
import com.syscv.utd.recursos.JPColor;
import com.syscv.utd.reportes.ReporteTallerExterno;
import com.syscv.utd.reportes.ReporteTallerInterno;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Jonathan
 */
public class JIFTallerExterno extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo1;
    private DefaultTableModel modelo;
    private int id_vehiculo,consecutivo, id_sistema,id_sistema1 , id_itemsistemas, id_mto_externo, id_tabla;
    private Mantenimientos_Externos mtoext;
    private Dtalle_mto_externo dtmtoext;
    private Dao_mto_ext daoMtoExt;
    private Dao_Dtlle_mto_externo daodt;
    private int id_mto_interno, id_dt_mto_interno;
    
    
    ConexionBD conexion=new ConexionBD();
    private ReporteTallerInterno reporteTallerInterno;
    private ReporteTallerExterno reporteTallerExterno;
    
    public JIFTallerExterno() {
        initComponents();
        
        Color c1=new Color(66,111,166);
        Color c2=new Color(102,174,118);
        JPColor miColor=new JPColor(c1,c2);
        miColor.setSize(this.getSize());
        p_encabezado.add(miColor);
        
        cargarItemVehiculo();
        cargarItemTaller();
        cargarItemSistema();
        cargarItemSistema1();
        cargarItemTipoMto();
        
        modelo1=new DefaultTableModel();
        
        modelo=new DefaultTableModel();
       
        
 
        
        modelo.addColumn("ID");
        modelo.addColumn("Item del Sistema");
        modelo.addColumn("Descripción");
        modelo.addColumn("Can");
        modelo.addColumn("um");
        modelo.addColumn("Observación");
        modelo.addColumn("ID Mto. Interno");
        modelo.addColumn("ID DT. Mto.Interno");
        
        modelo1.addColumn("ID");
        modelo1.addColumn("ID DT");
        modelo1.addColumn("Fecha");
        modelo1.addColumn("Servicio Mecánico Interno");
        modelo1.addColumn("Novedad");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Detalle_TE = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_obse = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txt_cant = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_um = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_guardar_det = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cb_sistema = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cb_item = new javax.swing.JComboBox();
        btn_cancelar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txt_id_mto_interno = new javax.swing.JTextField();
        btn_vincular_1 = new javax.swing.JButton();
        txt_id_dt_mto_interno = new javax.swing.JTextField();
        JD_Pendientes = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_mtointerno = new javax.swing.JTable();
        btn_vincular = new javax.swing.JButton();
        btn_reporte = new javax.swing.JButton();
        JD_Mod_Detalle_TE = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_descripcion1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_obse1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        txt_cant1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_um1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btn_guardar_det1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cb_sistema1 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        cb_item1 = new javax.swing.JComboBox();
        btn_cancelar1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txt_id_mto_interno1 = new javax.swing.JTextField();
        txt_id_dt_mto_interno1 = new javax.swing.JTextField();
        btn_vincular_2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_vehiculo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cb_taller = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txt_consecutivo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_solicita = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox();
        p_encabezado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_detalle = new javax.swing.JTable();
        btn_mod = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();

        JD_Detalle_TE.setTitle("Detalle Mto. Taller Externo");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Trabajo a realizar *");

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane4.setViewportView(txt_descripcion);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Observación");

        txt_obse.setColumns(20);
        txt_obse.setRows(5);
        jScrollPane5.setViewportView(txt_obse);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Cantidad *");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("UM *");

        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        jLabel18.setText("* Campos Obligatorios");

        btn_guardar_det.setText("Aceptar");
        btn_guardar_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_detActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Sistema Vehiculo");

        cb_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sistemaActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Sub -Sistema *");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Vincular-Servicio Mto. Interno");

        txt_id_mto_interno.setEditable(false);
        txt_id_mto_interno.setText("0");

        btn_vincular_1.setText("Vincular");
        btn_vincular_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vincular_1ActionPerformed(evt);
            }
        });

        txt_id_dt_mto_interno.setEditable(false);
        txt_id_dt_mto_interno.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_guardar_det)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(txt_id_mto_interno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_dt_mto_interno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_vincular_1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 22, Short.MAX_VALUE))
                            .addComponent(cb_item, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txt_cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_um, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_id_mto_interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vincular_1)
                    .addComponent(txt_id_dt_mto_interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar_det)
                    .addComponent(btn_cancelar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout JD_Detalle_TELayout = new javax.swing.GroupLayout(JD_Detalle_TE.getContentPane());
        JD_Detalle_TE.getContentPane().setLayout(JD_Detalle_TELayout);
        JD_Detalle_TELayout.setHorizontalGroup(
            JD_Detalle_TELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_Detalle_TELayout.setVerticalGroup(
            JD_Detalle_TELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_Detalle_TELayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JD_Pendientes.setTitle("Pendiente Mto. Taller Externo");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mto. Interno - Requerimiento Mto. Externo"));

        tb_mtointerno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_mtointerno);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );

        btn_vincular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/add.png"))); // NOI18N
        btn_vincular.setToolTipText("Vincular Mto. Interno");
        btn_vincular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_vincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vincularActionPerformed(evt);
            }
        });

        btn_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/reporte.png"))); // NOI18N
        btn_reporte.setToolTipText("Ver Reporte Mto. Interno");
        btn_reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_PendientesLayout = new javax.swing.GroupLayout(JD_Pendientes.getContentPane());
        JD_Pendientes.getContentPane().setLayout(JD_PendientesLayout);
        JD_PendientesLayout.setHorizontalGroup(
            JD_PendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PendientesLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_PendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_vincular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        JD_PendientesLayout.setVerticalGroup(
            JD_PendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PendientesLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JD_PendientesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_vincular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JD_Mod_Detalle_TE.setTitle("Detalle Mto. Taller Externo");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Trabajo a realizar *");

        txt_descripcion1.setColumns(20);
        txt_descripcion1.setRows(5);
        jScrollPane6.setViewportView(txt_descripcion1);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Observación");

        txt_obse1.setColumns(20);
        txt_obse1.setRows(5);
        jScrollPane7.setViewportView(txt_obse1);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Cantidad *");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("UM *");

        jLabel25.setForeground(new java.awt.Color(153, 0, 0));
        jLabel25.setText("* Campos Obligatorios");

        btn_guardar_det1.setText("Aceptar");
        btn_guardar_det1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_det1ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Sistema Vehiculo");

        cb_sistema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sistema1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Sub -Sistema *");

        btn_cancelar1.setText("Cancelar");
        btn_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar1ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Vincular-Servicio Mto. Interno");

        txt_id_mto_interno1.setEditable(false);
        txt_id_mto_interno1.setText("0");

        txt_id_dt_mto_interno1.setEditable(false);
        txt_id_dt_mto_interno1.setText("0");

        btn_vincular_2.setText("Vincular");
        btn_vincular_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vincular_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardar_det1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar1)
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_sistema1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txt_cant1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(txt_um1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addComponent(cb_item1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(txt_id_mto_interno1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_dt_mto_interno1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_vincular_2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane7)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cb_sistema1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(cb_item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txt_cant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_um1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_id_mto_interno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vincular_2)
                    .addComponent(txt_id_dt_mto_interno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar_det1)
                    .addComponent(btn_cancelar1))
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_Mod_Detalle_TELayout = new javax.swing.GroupLayout(JD_Mod_Detalle_TE.getContentPane());
        JD_Mod_Detalle_TE.getContentPane().setLayout(JD_Mod_Detalle_TELayout);
        JD_Mod_Detalle_TELayout.setHorizontalGroup(
            JD_Mod_Detalle_TELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_Mod_Detalle_TELayout.setVerticalGroup(
            JD_Mod_Detalle_TELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Remisión Taller Externo --UTDVVCC--");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Remisión Talleres Externos"));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("ID MTO EXTERNO");

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(255, 255, 51));
        txt_id.setForeground(new java.awt.Color(255, 0, 51));
        txt_id.setText("0");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Vehiculo / Equipo *");

        cb_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vehiculoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Proveedor / Taller  *");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Consecutivo Equipo/Vehiculo");

        txt_consecutivo.setEditable(false);
        txt_consecutivo.setBackground(new java.awt.Color(255, 255, 51));
        txt_consecutivo.setForeground(new java.awt.Color(255, 0, 51));
        txt_consecutivo.setText("0");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Solicita");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Campos Obligatorios *");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Tipo Mantenimiento *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_vehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(184, 184, 184))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_consecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_solicita, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_taller, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_consecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cb_taller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt_solicita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardar)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("REMISIÓN A TALLER DE MECÁNICA EXTERNO");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/taller.png"))); // NOI18N

        javax.swing.GroupLayout p_encabezadoLayout = new javax.swing.GroupLayout(p_encabezado);
        p_encabezado.setLayout(p_encabezadoLayout);
        p_encabezadoLayout.setHorizontalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(107, 107, 107))
        );
        p_encabezadoLayout.setVerticalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tb_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tb_detalle);

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/mod_detalle.png"))); // NOI18N
        btn_mod.setBorderPainted(false);
        btn_mod.setContentAreaFilled(false);
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/delete.png"))); // NOI18N
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/add.png"))); // NOI18N
        btn_agregar.setBorderPainted(false);
        btn_agregar.setContentAreaFilled(false);
        btn_agregar.setEnabled(false);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_mod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminar)
                .addContainerGap(135, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_imprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(jButton5)
                    .addComponent(btn_imprimir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vehiculoActionPerformed
            try {
            Vehiculo v=(Vehiculo) cb_vehiculo.getSelectedItem();
            id_vehiculo=v.getId_vehiculo();
            

            ResultSet obj=conexion.executeQuery("SELECT consecutivo_mto_externo +1 AS consecutivo FROM utilidades.vehiculos_equipos WHERE id_vehiculo="+id_vehiculo+" ");
            
            if(obj.next())
            {
                consecutivo=obj.getInt("consecutivo");
                
                txt_consecutivo.setText(String.valueOf(consecutivo));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JIFTallerInterno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_vehiculoActionPerformed

    private void btn_vincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vincularActionPerformed
        
        
        
        if(tb_mtointerno.isRowSelected(tb_mtointerno.getSelectedRow()))
            {
                id_mto_interno = (Integer) tb_mtointerno.getValueAt(tb_mtointerno.getSelectedRow(), 0);    
                id_dt_mto_interno=(Integer)tb_mtointerno.getValueAt(tb_mtointerno.getSelectedRow(), 1);
             
                txt_id_mto_interno.setText(String.valueOf(id_mto_interno));
                txt_id_dt_mto_interno.setText(String.valueOf(id_dt_mto_interno));
                
                JD_Pendientes.dispose();
       
              
     
            }else
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_vincularActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
      
        
        if(tb_mtointerno.isRowSelected(tb_mtointerno.getSelectedRow()))
            {
                id_mto_interno = (Integer) tb_mtointerno.getValueAt(tb_mtointerno.getSelectedRow(), 0);    
                id_dt_mto_interno=(Integer) tb_mtointerno.getValueAt(tb_mtointerno.getSelectedRow(), 1);
             
                reporteTallerInterno=new ReporteTallerInterno();
                reporteTallerInterno.ejecutarReporte(id_mto_interno);
                
       
              
     
            }else
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_reporteActionPerformed

    private void cb_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sistemaActionPerformed
            Sistemas s=(Sistemas) cb_sistema.getSelectedItem();
            id_sistema=s.getId();
            
            cb_item.removeAllItems();
            cargarItemSubsistema(id_sistema);
    }//GEN-LAST:event_cb_sistemaActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try {
            mtoext=new Mantenimientos_Externos();
            daoMtoExt=new Dao_mto_ext();
            
            int id_taller=0;
            int id_usuario=0;
            int id_tipo_mto;
            
            
            mtoext.setFecha_reg(new Date());
            id_usuario=MDIPrincipal.getvSeccion();
            mtoext.setId_usuario(id_usuario);
            
            TallerExterno t=(TallerExterno) cb_taller.getSelectedItem();
            id_taller=t.getId();
            mtoext.setId_taller(id_taller);
            
           // Vehiculo v=(Vehiculo)cb_vehiculo.getSelectedItem();
            //id_vehiculo=v.getId_vehiculo();
            
            Tipo_Mto tipo=(Tipo_Mto) cb_tipo.getSelectedItem();
            id_tipo_mto=tipo.getId();
            
            mtoext.setId_vehiculo(id_vehiculo);
            mtoext.setTipo_mto(id_tipo_mto);
            
            mtoext.setSolicita(txt_solicita.getText());
            mtoext.setConsecutivo_vehiculo(consecutivo);
            
            daoMtoExt.guardar(mtoext);
            
            btn_guardar.setEnabled(false);
            cb_taller.setEnabled(false);
            cb_vehiculo.setEnabled(false);
            txt_solicita.setEditable(false);
            
            btn_agregar.setEnabled(true);
            id_mto_externo=Dao_mto_ext.getId();
            
            mtoInternos(id_vehiculo);
            
            txt_id.setText(String.valueOf(id_mto_externo));
            conexion.executeUpdateQuery("UPDATE utilidades.vehiculos_equipos SET consecutivo_mto_externo="+txt_consecutivo.getText()+" WHERE id_vehiculo="+id_vehiculo+"");
            //conexion.executeUpdateQuery("UPDATE mantenimientos_mecanica.mto_internos SET mto_externo=false WHERE id_mto_interno="+id_mto_interno+"");
            conexion.desconectar();
            
            JOptionPane.showMessageDialog(rootPane, "Se registro con exito el encabezado!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        JD_Detalle_TE.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        JD_Detalle_TE.pack();
        JD_Detalle_TE.setLocationRelativeTo(null);
        JD_Detalle_TE.setVisible(true);
        JD_Detalle_TE.setResizable(false);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_guardar_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_detActionPerformed
     try {
            dtmtoext=new Dtalle_mto_externo();
            daodt=new Dao_Dtlle_mto_externo();
            
            int id_itemsistema;
            
            dtmtoext.setCan(Integer.parseInt(txt_cant.getText()));
            dtmtoext.setDescripcion(txt_descripcion.getText());
            dtmtoext.setUm(txt_um.getText());
            dtmtoext.setObservacion(txt_obse.getText());
            
            ItemSistema i=(ItemSistema) cb_item.getSelectedItem();
            id_itemsistema=i.getId();
            
            dtmtoext.setItemsistema(id_itemsistema);
            dtmtoext.setId_mto_externo(id_mto_externo);
            
            dtmtoext.setId_mto_interno(id_mto_interno);
            dtmtoext.setIddt_mto_externo(id_dt_mto_interno);
            
            daodt.guardar(dtmtoext);
            
            LimpiarTablaDetalle();
            detalleTabla();
            
            txt_cant.setText("");
            txt_obse.setText("");
            txt_um.setText("");
            txt_descripcion.setText("");
            txt_id_mto_interno.setText("0");
            txt_id_dt_mto_interno.setText("0");
            
            btn_mod.setEnabled(true);
            btn_eliminar.setEnabled(true);
            
            String observacion="Se atiende novedad con el ID Mto.Externo "+ id_mto_externo +" y Consecutivo de vehiculo para Mto. Externo N° " + consecutivo;
            
            if(id_mto_interno>0 && id_dt_mto_interno>0)
            {
            
            conexion.executeUpdateQuery("UPDATE mantenimientos_mecanica.dt_mto_interno SET observacion='" +observacion+"', mto_externo='false' WHERE id_dt_mto_interno="+id_dt_mto_interno+"");
            conexion.desconectar();
            }
            
            JOptionPane.showMessageDialog(rootPane, "Se registro con exito el item.!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btn_guardar_detActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
         
        daodt=new Dao_Dtlle_mto_externo();
        
        
        if(tb_detalle.isRowSelected(tb_detalle.getSelectedRow()))
            {
                
                id_tabla = (int) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 0);
                id_mto_interno=(int) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 6);
                id_dt_mto_interno=(int) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 7);
               
                daodt.eliminar(id_tabla);
               
               LimpiarTablaDetalle();
                
               detalleTabla();
               
               String obse="";
               
               if(id_mto_interno >0 && id_dt_mto_interno>0)
               {
                  conexion.executeUpdateQuery("UPDATE mantenimientos_mecanica.dt_mto_interno SET mto_externo=true AND observacion='"+obse+"' WHERE id_dt_mto_interno="+id_dt_mto_interno+"");
                  conexion.desconectar();
               }
               
               
               JOptionPane.showMessageDialog(rootPane, "Se eliminó con exito el item");
                
            }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
       String descripcion, um,observacion;
       
       int can, itemsistema;
       
         if(tb_detalle.isRowSelected(tb_detalle.getSelectedRow()))
            {
                
        id_tabla = (Integer) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 0);    

        descripcion=(String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 2);
        can=(int) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 3);
        um=(String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 4);
        observacion= (String) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 5) ;      
        id_mto_interno=(int) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 6) ;
        id_dt_mto_interno=(int) tb_detalle.getValueAt(tb_detalle.getSelectedRow(), 7) ;
       
        txt_descripcion1.setText(descripcion);
       txt_cant1.setText(String.valueOf(can));
       txt_um1.setText(um);
       txt_obse1.setText(observacion);
                
                 JD_Mod_Detalle_TE.pack();
                 JD_Mod_Detalle_TE.setLocationRelativeTo(null);
                 JD_Mod_Detalle_TE.setVisible(true);
                 JD_Mod_Detalle_TE.setResizable(false);
                 
                 String obse="";
                 if(id_mto_interno>0 && id_dt_mto_interno>0)
                 {
                     conexion.executeUpdateQuery("UPDATE mantenimientos_mecanica.dt_mto_interno SET mto_externo=true AND observacion='"+obse+"' WHERE id_dt_mto_interno="+id_dt_mto_interno+"");
                     conexion.desconectar(); 
                     
                     JOptionPane.showMessageDialog(rootPane, "Vincule nuevamente el servicio del Mto. Interno si fuese necesario!");
                 }
          
            }else
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_guardar_det1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_det1ActionPerformed
        try {
            dtmtoext=new Dtalle_mto_externo();
            daodt=new Dao_Dtlle_mto_externo();
            
            int id_itemsistema;
            
            
            dtmtoext.setCan(Integer.parseInt(txt_cant1.getText()));
            dtmtoext.setDescripcion(txt_descripcion1.getText());
            dtmtoext.setUm(txt_um1.getText());
            dtmtoext.setObservacion(txt_obse1.getText());
            
            ItemSistema i=(ItemSistema) cb_item1.getSelectedItem();
            id_itemsistema=i.getId();
            
            dtmtoext.setItemsistema(id_itemsistema);
            dtmtoext.setIddt_mto_externo(id_tabla);
            
            daodt.actualizar(dtmtoext);
            
            LimpiarTablaDetalle();
            detalleTabla();
            btn_mod.setEnabled(true);
            btn_eliminar.setEnabled(true);
            
            JOptionPane.showMessageDialog(rootPane, "Se Actualizo con exito el item.!");
            
            JD_Mod_Detalle_TE.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
       
    }//GEN-LAST:event_btn_guardar_det1ActionPerformed

    private void cb_sistema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sistema1ActionPerformed
         Sistemas s=(Sistemas) cb_sistema1.getSelectedItem();
            id_sistema1=s.getId();
            
            cb_item1.removeAllItems();
            cargarItemSubsistema1(id_sistema1);
    }//GEN-LAST:event_cb_sistema1ActionPerformed

    private void btn_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar1ActionPerformed
        JD_Mod_Detalle_TE.dispose();
    }//GEN-LAST:event_btn_cancelar1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
    try {
        
        int opc=JOptionPane.showConfirmDialog(null,"Desea concluir El Reg. Mto. Taller Externo?", "Aviso!", JOptionPane.YES_NO_OPTION); 

        
        if(opc==JOptionPane.YES_OPTION)
        {
    
            this.dispose();
        }

      } catch (Exception ex) 
       {
          JOptionPane.showMessageDialog(rootPane, ex);
       } 
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        
         try {
        
        int opc=JOptionPane.showConfirmDialog(null,"Desea concluir El Reg. Mto. Taller Externo?", "Aviso!", JOptionPane.YES_NO_OPTION); 

        
        if(opc==JOptionPane.YES_OPTION)
        {
    
            
        if(tb_detalle.getRowCount()== 0 && tb_detalle.getSelectedRow()==-1)
        {
         
           throw new Exception("La Tabla detalle no tiene ningún item adicionado!");

        }
        
        reporteTallerExterno=new ReporteTallerExterno();
        
        reporteTallerExterno.ejecutarReporte(id_mto_externo);
        
        this.dispose();
      }

      } catch (Exception ex) 
       {
          JOptionPane.showMessageDialog(rootPane, ex);
       } 
        
        
        
       
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        reporteTallerExterno=new ReporteTallerExterno();
        
        reporteTallerExterno.ejecutarReporte(Integer.parseInt(txt_id.getText()));
        
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_vincular_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vincular_1ActionPerformed
        JD_Pendientes.pack();
        JD_Pendientes.setLocationRelativeTo(null);
        JD_Pendientes.setVisible(true);
        JD_Pendientes.setResizable(false);
     
    }//GEN-LAST:event_btn_vincular_1ActionPerformed

    private void btn_vincular_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vincular_2ActionPerformed
        JD_Pendientes.pack();
        JD_Pendientes.setLocationRelativeTo(null);
        JD_Pendientes.setVisible(true);
        JD_Pendientes.setResizable(false);
    }//GEN-LAST:event_btn_vincular_2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Detalle_TE;
    private javax.swing.JDialog JD_Mod_Detalle_TE;
    private javax.swing.JDialog JD_Pendientes;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelar1;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar_det;
    private javax.swing.JButton btn_guardar_det1;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JButton btn_vincular;
    private javax.swing.JButton btn_vincular_1;
    private javax.swing.JButton btn_vincular_2;
    private javax.swing.JComboBox cb_item;
    private javax.swing.JComboBox cb_item1;
    private javax.swing.JComboBox cb_sistema;
    private javax.swing.JComboBox cb_sistema1;
    private javax.swing.JComboBox cb_taller;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JComboBox cb_vehiculo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel p_encabezado;
    private javax.swing.JTable tb_detalle;
    private javax.swing.JTable tb_mtointerno;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_cant1;
    private javax.swing.JTextField txt_consecutivo;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextArea txt_descripcion1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id_dt_mto_interno;
    private javax.swing.JTextField txt_id_dt_mto_interno1;
    private javax.swing.JTextField txt_id_mto_interno;
    private javax.swing.JTextField txt_id_mto_interno1;
    private javax.swing.JTextArea txt_obse;
    private javax.swing.JTextArea txt_obse1;
    private javax.swing.JTextField txt_solicita;
    private javax.swing.JTextField txt_um;
    private javax.swing.JTextField txt_um1;
    // End of variables declaration//GEN-END:variables
      public void cargarItemVehiculo()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemVehiculo();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_vehiculo.addItem(lista.get(i));
            }
        }
    }
      
       public void cargarItemTaller()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemProveedor();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_taller.addItem(lista.get(i));
            }
        }
    }
      
       
        public void cargarItemSubsistema(int id)
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemSubsistema(id);
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_item.addItem(lista.get(i));
            }
        }
    }    
      
        
      
        public void cargarItemSubsistema1(int id)
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemSubsistema(id);
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_item1.addItem(lista.get(i));
            }
        }
    }    
    
          public void cargarItemSistema()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemSistema();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_sistema.addItem(lista.get(i));
            }
        }
    }  
          
          
         public void cargarItemSistema1()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemSistema();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_sistema1.addItem(lista.get(i));
            }
        }
    }         
       
       public void mtoInternos(int id_vehiculo)
       {
           ConexionBD conexion = new ConexionBD();
    
        ResultSet obj=conexion.executeQuery("SELECT m.id_mto_interno,dt.id_dt_mto_interno,m.fecha_reg,lab.labor, dt.novedades FROM mantenimientos_mecanica.mto_internos m JOIN mantenimientos_mecanica.dt_mto_interno dt ON dt.id_mto_interno=m.id_mto_interno JOIN utilidades.labor_mecanico lab ON lab.id_labor=dt.id_labor_mec WHERE dt.mto_externo=true AND m.id_vehiculo="+id_vehiculo+" ORDER BY m.id_mto_interno,dt.id_dt_mto_interno ASC ");
    
    
        try {
            while (obj.next())
            {
                
                Object [] datos = new Object[5];
                
                for (int i=0;i<5;i++)
                {
                    datos[i] =obj.getObject(i+1);
                }
                
                modelo1.addRow(datos);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(JIFTallerExterno.class.getName()).log(Level.SEVERE, null, ex);
        }
        tb_mtointerno.setModel(modelo1);
        setCellRender(tb_mtointerno);
        conexion.desconectar();
    
       }

         public void setCellRender(JTable table)
         {
            Enumeration<TableColumn> en = table.getColumnModel().getColumns();
            while (en.hasMoreElements()) {
                    TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
        }
     }  
        
          public void LimpiarTabla()
    {
  
        for(int i=modelo1.getRowCount()-1;i>=0;i--)
        {
            modelo1.removeRow(i);
            
        }
    }

          
          // Metodo para llenar la tabla detalle
       public void detalleTabla()
        {
       try
        {
            ConexionBD nueva=new ConexionBD();
            
            ResultSet obj=nueva.executeQuery("SELECT d.id_dt_mto_ex,(s.descripcion ||' '||i.descripcion)AS item, d.descripcion,d.can,d.um, d.observacion, d.id_mto_interno, d.id_dt_mto_interno FROM mantenimientos_mecanica.dte_mto_externo d JOIN utilidades.items_sistema i ON i.id=d.item_sistema JOIN utilidades.sistema_vehiculo s ON s.id_sistema=i.id_sistema WHERE d.id_mto_externo="+id_mto_externo+" ");
            
            
            
            while (obj.next()) 
        {
        
        Object [] datos = new Object[8];
        
     
        for (int i=0;i<8;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modelo.addRow(datos);
       
        }
           tb_detalle.setModel(modelo);
           
           
        TableColumnModel columnModel =tb_detalle.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(5);
        columnModel.getColumn(4).setPreferredWidth(5);
        columnModel.getColumn(5).setPreferredWidth(100);
          
           
            setCellRender(tb_detalle);
           nueva.desconectar();
       

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }



        }
      
     
      
    public void LimpiarTablaDetalle()
    {
  
        for(int i=modelo.getRowCount()-1;i>=0;i--)
        {
            modelo.removeRow(i);
            
        }
    }

    
      public void cargarItemTipoMto()
       {
           ControllerItemList control=new ControllerItemList();
           ArrayList lista=control.listarItemTipoMto();
           
           if(lista !=null)
           {
               int size=lista.size();
               for(int i=0; i<size; i++)
            {
                cb_tipo.addItem(lista.get(i));
            }
           }
           
           
       }

}
