/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.syscv.utd.presentacion;

import com.syscv.utd.conexionBD.ConexionBD;
import com.syscv.utd.dao.ctrlcom.VehiculoDao;
import com.syscv.utd.dao.ctrlcom.documentos.ManejoImagen;
import com.syscv.utd.dao.ctrlcom.documentos.imagen;
import com.syscv.utd.dao.general.Dao_Ficha_Tecnica;
import com.syscv.utd.entidades.ControllerItemList;
import com.syscv.utd.entidades.Ficha_tecnica;
import com.syscv.utd.entidades.Linea;
import com.syscv.utd.entidades.Tipo_Documentos_Vehi;
import com.syscv.utd.entidades.Vehiculo;
import com.syscv.utd.recursos.JPColor;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jonathan
 */
public class JIFVehiculosEquipos extends javax.swing.JInternalFrame {

    private ConexionBD conexion;
    private Vehiculo v;
    private VehiculoDao vehiDao;
    private int id_linea;
    private int id_vehiculo;
    private int id_vehiculo_img;
    private int id_vehiculo_doc;
    private Ficha_tecnica ficha;
    private Dao_Ficha_Tecnica daoFicha;
    private int id_ficha=0;
    private int id_usuario=MDIPrincipal.getvSeccion();
    private ManejoImagen mi=new ManejoImagen();
    private int id_tipo_doc;
    private DefaultListModel modListaImagen = new DefaultListModel();
    
    
    
    public JIFVehiculosEquipos() {
        
     
        initComponents();
        
        conexion=new ConexionBD();
        
        this.dc_inicio.setDate(new Date());
        this.dc_ven.setDate(new Date());
        
        Color c1=new Color(66,111,166);
        Color c2=new Color(102,174,118);
        JPColor miColor=new JPColor(c1,c2);
        miColor.setSize(this.getSize());
        p_encabezado.add(miColor);
        
        cargarItemVehiculo();
        cargarItemTipoDoc();
        
         try {
          ResultSet obj=conexion.executeQuery("SELECT name_combustible FROM utilidades.tipo_combustible ORDER BY name_combustible ASC");
        
         
             while(obj.next())
            {
                cb_tc.addItem(obj.getObject("name_combustible"));
            }
             
             
            ResultSet obj1=conexion.executeQuery("SELECT descripcion FROM utilidades.tipo_vehiculo ORDER BY descripcion ASC");
            
               while(obj1.next())
            {
                cb_tipo.addItem(obj1.getObject("descripcion"));
            }
            
//          ResultSet obj2=conexion.executeQuery("SELECT (ma.descripcion ||' - '|| li.descripcion)AS linea FROM utilidades.linea_vehiculo li JOIN utilidades.marca_vehiculo ma ON ma.id_marca=li.id_marca ORDER BY linea ASC");
//
//                  while(obj2.next())
//            {
//                cb_linea.addItem(obj2.getObject("linea"));
//            }  
               
               
              cargarItemLinea();
              panel_oculto.setVisible(false);
                  
         ResultSet obj3=conexion.executeQuery("SELECT nombre_centro_costos FROM utilidades.centrocostos ORDER BY nombre_centro_costos ASC");
      
                     while(obj3.next())
            {
                cb_costos.addItem(obj3.getObject("nombre_centro_costos"));
            }     
               
        } catch (SQLException ex) {
            Logger.getLogger(JIFVehiculosEquipos.class.getName()).log(Level.SEVERE, null, ex);
        
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        p_encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tp_general = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_tc = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cb_linea = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cb_costos = new javax.swing.JComboBox();
        cb_item = new javax.swing.JComboBox();
        btn_uardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        panel_oculto = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cb_otrotipocom = new javax.swing.JComboBox();
        btn_togle = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_carroceria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_chasis = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_serie = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_motor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        txt_cilindraje = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_can_pasa = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_vel_marcha_min = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_cap_aceite_motor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_cap_refri = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_cap_tan_com = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_tipo_cambi = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_cap_cam = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_tipo_dir = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_aceite_dir = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_tipo_dif = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_cap_ace_dif = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_rin = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_ref_llanta = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_presi_inf = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_ref_bateria = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_alternador = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txt_motor_arran = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_cancelar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        cb_vehiculo = new javax.swing.JComboBox();
        btn_buscar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_registros = new javax.swing.JComboBox();
        btnadjuntar = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Imagenes = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        FOTO = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        cb_registros1 = new javax.swing.JComboBox();
        btnadjuntar1 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cb_tipo_doc = new javax.swing.JComboBox();
        dc_inicio = new com.toedter.calendar.JDateChooser();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        dc_ven = new com.toedter.calendar.JDateChooser();
        ck_box_ven = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        txt_ndoc = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_Imagenes1 = new javax.swing.JList();
        jPanel11 = new javax.swing.JPanel();
        FOTO1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel6.setText("jLabel6");

        jLabel11.setText("jLabel11");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton2");

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Vehiculos-Equipos --UTDVVCC--");

        p_encabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Registro Vehiculos / Equipos");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/syscv/utd/recursos/Car.png"))); // NOI18N

        javax.swing.GroupLayout p_encabezadoLayout = new javax.swing.GroupLayout(p_encabezado);
        p_encabezado.setLayout(p_encabezadoLayout);
        p_encabezadoLayout.setHorizontalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_encabezadoLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_encabezadoLayout.setVerticalGroup(
            p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_encabezadoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Placa");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Combustible");

        cb_tc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cb_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tcActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Tipo");

        cb_tipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Linea");

        cb_linea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("C.Costos");

        cb_costos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cb_costos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_costosActionPerformed(evt);
            }
        });

        cb_item.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btn_uardar.setText("Guardar");
        btn_uardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("Combustible");

        cb_otrotipocom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cb_otrotipocom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_ocultoLayout = new javax.swing.GroupLayout(panel_oculto);
        panel_oculto.setLayout(panel_ocultoLayout);
        panel_ocultoLayout.setHorizontalGroup(
            panel_ocultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ocultoLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_otrotipocom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panel_ocultoLayout.setVerticalGroup(
            panel_ocultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ocultoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_ocultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_otrotipocom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        btn_togle.setText("Alterno");
        btn_togle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_togleStateChanged(evt);
            }
        });
        btn_togle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_togleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_uardar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panel_oculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(39, 39, 39)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(cb_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_togle)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_costos, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_linea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_cancelar))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cb_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_togle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_oculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cb_linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_costos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_uardar)
                    .addComponent(btn_cancelar))
                .addContainerGap())
        );

        tp_general.addTab("General", jPanel1);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Tipo Carroceria");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Modelo");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Chasis");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Serie");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("N° Motor");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Color");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Cilindraje");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("N° Pasajeros");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Peso Bruto");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Velocidad Marcha Minima");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Cap. Aceite del Motor");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Cap. del Refrigerante");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Cap. Tanque Combustible");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Tipo Caja de Cambios");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Cap. Caja de Cambios");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Tipo de Dirección");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Cap. Aceite de Dirección");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Tipo Diferencial");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Cap. Aceite Diferencial");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setText("N° Rin de rueda");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("Referencia de la llanta");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("Presión de Inflado");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setText("Referencia Bateria");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setText("Alternador");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel36.setText("Motor de Arranque");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        txt_cancelar1.setText("Cancelar");
        txt_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cancelar1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Vehiculo / Equipo"));

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setText("Vehiculo / Equipo");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_actualizar.setText("Actualizar");
        btn_actualizar.setEnabled(false);
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cap_tan_com)
                                    .addComponent(txt_cap_cam)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_cap_aceite_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel34))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ref_llanta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_cap_ace_dif, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_aceite_dir)
                                    .addComponent(txt_ref_bateria))))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cap_refri, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tipo_dir)
                                    .addComponent(txt_tipo_dif)
                                    .addComponent(txt_rin)
                                    .addComponent(txt_presi_inf)
                                    .addComponent(txt_alternador)
                                    .addComponent(txt_tipo_cambi))))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(48, 48, 48)
                                        .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_motor_arran)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_cilindraje))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_vel_marcha_min)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(39, 39, 39)
                                .addComponent(txt_chasis))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_can_pasa, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(txt_peso))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cancelar1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(txt_can_pasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txt_vel_marcha_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(txt_motor_arran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_cap_aceite_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txt_cap_refri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_cap_tan_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txt_tipo_cambi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_cap_cam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txt_tipo_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_aceite_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txt_tipo_dif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_cap_ace_dif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txt_rin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_ref_llanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txt_presi_inf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txt_ref_bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txt_alternador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(txt_cancelar1)
                    .addComponent(btn_actualizar))
                .addContainerGap())
        );

        tp_general.addTab("Ficha Técnica", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjuntar archivos"));

        jLabel3.setText("Registro Fotografico Vehiculo / Equipo");

        cb_registros.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        cb_registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_registrosActionPerformed(evt);
            }
        });

        btnadjuntar.setText("Adjuntar");
        btnadjuntar.setToolTipText("Nota: Solo se admiten archivos JPG de peso maximo 1 Mb. Se recomiendan archivos de resolución 800 x 600 pixeles");
        btnadjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadjuntarActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 51, 51));
        jLabel37.setText("Nota: Solo se permiten archivos formato imagen (JPG). Y Tamaño max a (50 kb).  ");

        jLabel39.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 51, 51));
        jLabel39.setText("El nombre del archivo deber ser la placa del vehiculo/Equipo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_registros, 0, 561, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnadjuntar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel39))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnadjuntar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 300));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        Lista_Imagenes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista_Imagenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_ImagenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lista_Imagenes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(320, 300));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        FOTO.setText("FOTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel7.add(FOTO, gridBagConstraints);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tp_general.addTab("Subir Foto", jPanel4);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Adjuntar archivos"));

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setText(" Vehiculo / Equipo *");

        cb_registros1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        cb_registros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_registros1ActionPerformed(evt);
            }
        });

        btnadjuntar1.setText("Adjuntar");
        btnadjuntar1.setToolTipText("Nota: Solo se admiten archivos JPG de peso maximo 1 Mb. Se recomiendan archivos de resolución 800 x 600 pixeles");
        btnadjuntar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadjuntar1ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 51, 51));
        jLabel41.setText("Nota: Solo se permiten archivos formato imagen (JPG). Y Tamaño max a (500 kb).  ");

        jLabel42.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 51, 51));
        jLabel42.setText("El nombre del archivo deber ser la placa del vehiculo/Equipo y la inicial del tipo de documento");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel43.setText("Tipo de Doc *");

        dc_inicio.setEnabled(false);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setText("Fecha Inicio");

        jLabel45.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel45.setText("Fecha Vencimiento");

        dc_ven.setEnabled(false);

        ck_box_ven.setText("Doc. tiene Vencimiento");
        ck_box_ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_box_venActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setText("N° de Documento *");

        jLabel47.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 51, 51));
        jLabel47.setText("* Campos Obligatorios");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnadjuntar1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ndoc, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dc_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dc_ven, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ck_box_ven))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(10, 10, 10)
                                .addComponent(cb_registros1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel43))
                            .addComponent(jLabel41))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cb_tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_registros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel43)
                    .addComponent(cb_tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46)
                            .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(dc_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45)
                        .addComponent(dc_ven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ck_box_ven))
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnadjuntar1))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel47)))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 300));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        Lista_Imagenes1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista_Imagenes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_Imagenes1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Lista_Imagenes1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel10.add(jScrollPane2, gridBagConstraints);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(320, 300));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        FOTO1.setText("DOCUMENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel11.add(FOTO1, gridBagConstraints);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
        );

        tp_general.addTab("Documentación", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tp_general)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tp_general))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_costosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_costosActionPerformed
         try
        {
            ConexionBD nueva=new ConexionBD();
            
            int id_ccostos=0;

            if(cb_costos.getSelectedItem()!=null)
            {
                String centro=cb_costos.getSelectedItem().toString();
                ResultSet obj=nueva.executeQuery("SELECT id_centrocostos FROM utilidades.centrocostos WHERE nombre_centro_costos='"+centro+"'");

                while(obj.next())
                {
                    id_ccostos=obj.getInt("id_centrocostos");
                }
                cb_item.removeAllItems();
            }

            ResultSet obj2=nueva.executeQuery("SELECT nombre_item_ccostos FROM utilidades.itemccostos WHERE id_centrocostos="+id_ccostos+" ");

            while(obj2.next())
            {
                cb_item.addItem(obj2.getObject("nombre_item_ccostos"));
            }
            nueva.desconectar();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cb_costosActionPerformed

    private void btn_uardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uardarActionPerformed
        try
            
        {
            
            v=new Vehiculo();
            vehiDao=new VehiculoDao();
            int idtc=0;
            int id_tipo=0;
            int id_mixto=0;
            
            int id_item=0;
            
            Date fecha=new Date();
            
            v.setPlaca(txt_placa.getText());
           
             if(cb_tc.getSelectedItem()!=null)
            {
            String combus=cb_tc.getSelectedItem().toString();
            
            ResultSet obj=conexion.executeQuery("SELECT id_tipo_com FROM utilidades.tipo_combustible WHERE name_combustible='"+combus+"'");
            
             
                  while(obj.next())
                  {
                      idtc=obj.getInt("id_tipo_com");
                  } 
         
            }
             
            if( btn_togle.isSelected()==true)
            {
                  if(cb_otrotipocom.getSelectedItem()!=null)
            {
            String combus=cb_otrotipocom.getSelectedItem().toString();
            
            ResultSet objotro=conexion.executeQuery("SELECT id_tipo_com FROM utilidades.tipo_combustible WHERE name_combustible='"+combus+"'");
            
             
                  while(objotro.next())
                  {
                      id_mixto=objotro.getInt("id_tipo_com");
                  } 
               
            }
                  v.setId_mixto(id_mixto);
            }else
            {
                v.setId_mixto(idtc);
            }
                
                
             v.setId_tipocom(idtc);
             
            if(cb_tipo.getSelectedItem()!=null)
            {
            String tipo=cb_tipo.getSelectedItem().toString();
            
            ResultSet obj1=conexion.executeQuery("SELECT id_tipo_vehi FROM utilidades.tipo_vehiculo WHERE descripcion='"+tipo+"'");
            
             
                  while(obj1.next())
                  {
                      id_tipo=obj1.getInt("id_tipo_vehi");
                  } 
         
            }   
            
            v.setId_tipovehi(id_tipo);
            
        Linea li=(Linea) cb_linea.getSelectedItem();
        id_linea=li.getId_linea();
        
      
        System.out.println(id_linea);
        v.setId_linea(id_linea);
        
        
        if(cb_item.getSelectedItem()!=null)
            {
            String item=cb_item.getSelectedItem().toString();
            
            ResultSet obj2=conexion.executeQuery("SELECT id_item_ccostos FROM utilidades.itemccostos WHERE nombre_item_ccostos='"+item+"'");
            
             
                  while(obj2.next())
                  {
                      id_item=obj2.getInt("id_item_ccostos");
                  } 
         
            }   
        
            v.setId_item(id_item);
            v.setFecha(fecha);
            v.setId_usuario(id_usuario);
            
            
            vehiDao.guardar(v);
            limpiar();
            
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_uardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_togleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_togleActionPerformed
         try {
            panel_oculto.setVisible(true);
         
            ResultSet obj=conexion.executeQuery("SELECT name_combustible FROM utilidades.tipo_combustible ORDER BY name_combustible ASC");
            
            cb_otrotipocom.removeAllItems();
            while(obj.next())
            {
                cb_otrotipocom.addItem(obj.getObject("name_combustible"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JIFVehiculosEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_togleActionPerformed

    private void btn_togleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_togleStateChanged
        if(btn_togle.isSelected()==false)
        {
            panel_oculto.setVisible(false);
        }
    }//GEN-LAST:event_btn_togleStateChanged

    private void cb_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tcActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        Vehiculo v=(Vehiculo) cb_vehiculo.getSelectedItem();
        id_vehiculo=v.getId_vehiculo();
        
        
        ficha=new Ficha_tecnica();
        daoFicha=new Dao_Ficha_Tecnica();
        
        String tipo_carroceria, modelo,serie, chasis, n_motor, color, cilindraje, n_pasajeros, motor_arranque, v_marcha_minima, peso_bruto, cap_aceite_motor, cap_refrigerante,cap_tan_combustible,tipo_caja_cambios,cap_caja_cambios,tipo_direccion,cap_aceite_direccion, tipo_diferencial,cap_aceite_diferencial, n_rin_rueda, referencia_llanta, presion_inflado, referencia_bateria,alternador; 
            
        tipo_carroceria=txt_carroceria.getText();
        modelo=txt_modelo.getText();
        serie=txt_serie.getText();
        chasis=txt_chasis.getText();
        n_motor=txt_motor.getText();
        color=txt_color.getText();
        cilindraje=txt_cilindraje.getText();
        n_pasajeros=txt_can_pasa.getText();
        motor_arranque=txt_motor_arran.getText();
        v_marcha_minima=txt_vel_marcha_min.getText();
        peso_bruto=txt_peso.getText();
        cap_aceite_motor=txt_cap_aceite_motor.getText();
        cap_refrigerante=txt_cap_refri.getText();
        cap_tan_combustible=txt_cap_tan_com.getText();
        tipo_caja_cambios=txt_tipo_cambi.getText();
        cap_caja_cambios=txt_cap_cam.getText();
        tipo_direccion=txt_tipo_dir.getText();
        cap_aceite_direccion=txt_aceite_dir.getText();
        tipo_diferencial=txt_tipo_dif.getText();
        cap_aceite_diferencial=txt_cap_ace_dif.getText();
        n_rin_rueda=txt_rin.getText();
        referencia_llanta=txt_ref_llanta.getText();
        presion_inflado=txt_presi_inf.getText();
        referencia_bateria=txt_ref_bateria.getText();
        alternador=txt_alternador.getText();
        
        
        ficha.setTipo_carroceria(tipo_carroceria);
        ficha.setModelo(modelo);
        ficha.setSerie(serie);
        ficha.setChasis(chasis);
        ficha.setN_motor(n_motor);
        ficha.setColor(color);
        ficha.setCilindraje(cilindraje);
        ficha.setN_pasajeros(n_pasajeros);
        ficha.setMotor_arranque(motor_arranque);
        ficha.setV_marcha_minima(v_marcha_minima);
        ficha.setPeso_bruto(peso_bruto);
        ficha.setCap_aceite_motor(cap_aceite_motor);
        ficha.setCap_refrigerante(cap_refrigerante);
        ficha.setCap_tan_combustible(cap_tan_combustible);
        ficha.setTipo_caja_cambios(tipo_caja_cambios);
        ficha.setCap_caja_cambios(cap_caja_cambios);
        ficha.setTipo_direccion(tipo_direccion);
        ficha.setCap_aceite_direccion(cap_aceite_direccion);
        ficha.setTipo_diferencial(tipo_diferencial);
        ficha.setCap_aceite_diferencial(cap_aceite_diferencial);
        ficha.setN_rin_rueda(n_rin_rueda);
        ficha.setReferencia_llanta(referencia_llanta);
        ficha.setPresion_inflado(presion_inflado);
        ficha.setReferencia_bateria(referencia_bateria);
        ficha.setAlternador(alternador);
        ficha.setId_vehiculo(id_vehiculo);
        
        ficha.setId_usuario(id_usuario);
        ficha.setFecha_crea(new Date());
        
        try {
            
         ResultSet obj=conexion.executeQuery("SELECT ficha_tecnica FROM utilidades.vehiculos_equipos WHERE ficha_tecnica=true AND id_vehiculo="+id_vehiculo+"");
          
         if(obj.next()==false)
         {
            
            daoFicha.guardar(ficha);
            
            conexion.executeUpdateQuery("UPDATE utilidades.vehiculos_equipos SET ficha_tecnica=true WHERE id_vehiculo="+id_vehiculo+"");
            conexion.desconectar();
            
            limpiar();
      
          } else
         {
             JOptionPane.showMessageDialog(rootPane, "No se pudo crear la ficha Técnica.\nLa ficha técnica ya ha sido creada anteriormente.");
         }
         
     
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        Vehiculo v=(Vehiculo) cb_vehiculo.getSelectedItem();
        id_vehiculo=v.getId_vehiculo();
        buscarFichaTecnica(id_vehiculo);
        
        cb_vehiculo.setEnabled(false);
        btn_actualizar.setEnabled(true);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
          Vehiculo v=(Vehiculo) cb_vehiculo.getSelectedItem();
        id_vehiculo=v.getId_vehiculo();
        
        
        ficha=new Ficha_tecnica();
        daoFicha=new Dao_Ficha_Tecnica();
        
        String tipo_carroceria, modelo,serie, chasis, n_motor, color, cilindraje, n_pasajeros, motor_arranque, v_marcha_minima, peso_bruto, cap_aceite_motor, cap_refrigerante,cap_tan_combustible,tipo_caja_cambios,cap_caja_cambios,tipo_direccion,cap_aceite_direccion, tipo_diferencial,cap_aceite_diferencial, n_rin_rueda, referencia_llanta, presion_inflado, referencia_bateria,alternador; 
            
        tipo_carroceria=txt_carroceria.getText();
        modelo=txt_modelo.getText();
        serie=txt_serie.getText();
        chasis=txt_chasis.getText();
        n_motor=txt_motor.getText();
        color=txt_color.getText();
        cilindraje=txt_cilindraje.getText();
        n_pasajeros=txt_can_pasa.getText();
        motor_arranque=txt_motor_arran.getText();
        v_marcha_minima=txt_vel_marcha_min.getText();
        peso_bruto=txt_peso.getText();
        cap_aceite_motor=txt_cap_aceite_motor.getText();
        cap_refrigerante=txt_cap_refri.getText();
        cap_tan_combustible=txt_cap_tan_com.getText();
        tipo_caja_cambios=txt_tipo_cambi.getText();
        cap_caja_cambios=txt_cap_cam.getText();
        tipo_direccion=txt_tipo_dir.getText();
        cap_aceite_direccion=txt_aceite_dir.getText();
        tipo_diferencial=txt_tipo_dif.getText();
        cap_aceite_diferencial=txt_cap_ace_dif.getText();
        n_rin_rueda=txt_rin.getText();
        referencia_llanta=txt_ref_llanta.getText();
        presion_inflado=txt_presi_inf.getText();
        referencia_bateria=txt_ref_bateria.getText();
        alternador=txt_alternador.getText();
        
        
        ficha.setTipo_carroceria(tipo_carroceria);
        ficha.setModelo(modelo);
        ficha.setSerie(serie);
        ficha.setChasis(chasis);
        ficha.setN_motor(n_motor);
        ficha.setColor(color);
        ficha.setCilindraje(cilindraje);
        ficha.setN_pasajeros(n_pasajeros);
        ficha.setMotor_arranque(motor_arranque);
        ficha.setV_marcha_minima(v_marcha_minima);
        ficha.setPeso_bruto(peso_bruto);
        ficha.setCap_aceite_motor(cap_aceite_motor);
        ficha.setCap_refrigerante(cap_refrigerante);
        ficha.setCap_tan_combustible(cap_tan_combustible);
        ficha.setTipo_caja_cambios(tipo_caja_cambios);
        ficha.setCap_caja_cambios(cap_caja_cambios);
        ficha.setTipo_direccion(tipo_direccion);
        ficha.setCap_aceite_direccion(cap_aceite_direccion);
        ficha.setTipo_diferencial(tipo_diferencial);
        ficha.setCap_aceite_diferencial(cap_aceite_diferencial);
        ficha.setN_rin_rueda(n_rin_rueda);
        ficha.setReferencia_llanta(referencia_llanta);
        ficha.setPresion_inflado(presion_inflado);
        ficha.setReferencia_bateria(referencia_bateria);
        ficha.setAlternador(alternador);
        ficha.setId_vehiculo(id_vehiculo);
        
        ficha.setId_usuario(id_usuario);
        ficha.setFecha_crea(new Date());
        ficha.setId_ficha(id_ficha);
        
       
            
        try {
            daoFicha.actualizar(ficha);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,  ex);
        }
            
            conexion.desconectar();
            
            limpiar();
            cb_vehiculo.setEnabled(true);
            btn_actualizar.setEnabled(false);
          
         
     
      
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txt_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cancelar1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_txt_cancelar1ActionPerformed

    private void cb_registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_registrosActionPerformed
        Actualizar_lista();
    }//GEN-LAST:event_cb_registrosActionPerformed

    private void btnadjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadjuntarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter( new FileNameExtensionFilter("Archivo de Imagen","jpg") );
        fileChooser.setCurrentDirectory(new java.io.File("e:/imagenes_tmp/"));
        int result = fileChooser.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ){
            //obtiene ruta y nombre del archivo
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            String name = fileChooser.getSelectedFile().getName();
            Vehiculo v=(Vehiculo) cb_registros.getSelectedItem();
            id_vehiculo_img=v.getId_vehiculo();
            try {
                
                ResultSet obj =conexion.executeQuery("SELECT foto FROM utilidades.vehiculos_equipos WHERE foto=true AND id_vehiculo="+id_vehiculo_img+"");
                
                        
                        if (obj.next()==true)
                        {
                            JOptionPane.showMessageDialog(rootPane, "No se puede cargar la foto. El vehiculo/Equpo ya tiene foto asignada.");
                        }
                  else
                        {
                if( mi.guardarfoto2( GenerarCodigo() , name, ruta, id_vehiculo_img) )
                {
                    JOptionPane.showMessageDialog(this,"Documento ["+name+"] almacenado");
                    Actualizar_lista();
                   
                    
                    conexion.executeUpdateQuery("UPDATE utilidades.vehiculos_equipos SET foto=true WHERE id_vehiculo="+id_vehiculo_img+"");
                            conexion.desconectar();
                 
                }
              } 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnadjuntarActionPerformed

    private void Lista_ImagenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_ImagenesMouseClicked
        int index = this.Lista_Imagenes.getSelectedIndex();//obtiene index seleccionado
        if( index != -1)
        {
            //Extrae la clase imagen que corresponde a la posición donde se hizo un clic
            imagen img = (imagen)this.modListaImagen.getElementAt(index);
            //redimensiona imagen

            double alto = img.getArchivo().getHeight(null) / Math.ceil(img.getArchivo().getHeight(null)/300f) ;
            double ancho =img.getArchivo().getWidth(null) / Math.ceil(img.getArchivo().getWidth(null)/500f) ;
            Icon icon = new ImageIcon( img.getArchivo().getScaledInstance((int)ancho,(int)alto, Image.SCALE_AREA_AVERAGING) );
            this.FOTO.setText("");
            this.FOTO.setIcon( icon  );//coloca imagen en el JLabel
        }

    }//GEN-LAST:event_Lista_ImagenesMouseClicked

    private void cb_registros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_registros1ActionPerformed
        Actualizar_lista2();
    }//GEN-LAST:event_cb_registros1ActionPerformed

    private void btnadjuntar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadjuntar1ActionPerformed
       
        
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter( new FileNameExtensionFilter("Archivo de Imagen","jpg") );
        fileChooser.setCurrentDirectory(new java.io.File("e:/imagenes_tmp/"));
        int result = fileChooser.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ){
            //obtiene ruta y nombre del archivo
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            String name = fileChooser.getSelectedFile().getName();
            
            Tipo_Documentos_Vehi t=(Tipo_Documentos_Vehi) cb_tipo_doc.getSelectedItem();
            id_tipo_doc=t.getId_tipo_doc();
            
            Vehiculo v=(Vehiculo) cb_registros1.getSelectedItem();
            id_vehiculo_doc=v.getId_vehiculo();
            
            Date fecha_ini=dc_inicio.getDate();
            Date fecha_vence=dc_ven.getDate();
            
            java.sql.Date sqlFecha_ini = new java.sql.Date(fecha_ini.getTime());
            java.sql.Date sqlFecha_vence = new java.sql.Date(fecha_vence.getTime());

            
            
            String n_doc=txt_ndoc.getText();
            
            boolean vence=false;
            
            if(ck_box_ven.isSelected())
            {
                vence=true;
            }
            
            
           
            try {
                
                ResultSet obj =conexion.executeQuery("SELECT id_doc FROM utilidades.documentacion_vehiculo WHERE id_vehiculo="+id_vehiculo_doc+" AND activo=true AND id_tipo_doc="+id_tipo_doc+" ");
                
                        
                        if (obj.next()==true)
                        {
                            JOptionPane.showMessageDialog(rootPane, "No se puede cargar el documento. El vehiculo/Equpo ya tiene asignado este tipo de documento y esta vigente");
                        }
                  else
                        {
                            
                            
                            
                if( mi.guardardoc(GenerarCodigo() , name, ruta, id_vehiculo_doc, vence,id_tipo_doc,id_usuario,sqlFecha_ini,sqlFecha_vence,n_doc ) )
                {
                    JOptionPane.showMessageDialog(this,"Documento ["+name+"] almacenado");
                    Actualizar_lista2();
                   
                    
                    conexion.desconectar();
                 
                }
              } 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnadjuntar1ActionPerformed

    private void Lista_Imagenes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_Imagenes1MouseClicked
        int index = this.Lista_Imagenes1.getSelectedIndex();//obtiene index seleccionado
        if( index != -1)
        {
            //Extrae la clase imagen que corresponde a la posición donde se hizo un clic
            imagen img = (imagen)this.modListaImagen.getElementAt(index);
            //redimensiona imagen

            double alto = img.getArchivo().getHeight(null) / Math.ceil(img.getArchivo().getHeight(null)/300f) ;
            double ancho =img.getArchivo().getWidth(null) / Math.ceil(img.getArchivo().getWidth(null)/1200f) ;
            Icon icon = new ImageIcon( img.getArchivo().getScaledInstance((int)ancho,(int)alto, Image.SCALE_AREA_AVERAGING) );
            this.FOTO1.setText("");
            this.FOTO1.setIcon( icon  );//coloca imagen en el JLabel
        }

    }//GEN-LAST:event_Lista_Imagenes1MouseClicked

    private void ck_box_venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_box_venActionPerformed
        
        if(ck_box_ven.isSelected())
        {
            dc_inicio.setEnabled(true);
            dc_ven.setEnabled(true);
        }
        else
        {
            dc_inicio.setEnabled(false);
            dc_ven.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_ck_box_venActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FOTO;
    private javax.swing.JLabel FOTO1;
    private javax.swing.JList Lista_Imagenes;
    private javax.swing.JList Lista_Imagenes1;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JToggleButton btn_togle;
    private javax.swing.JButton btn_uardar;
    private javax.swing.JButton btnadjuntar;
    private javax.swing.JButton btnadjuntar1;
    private javax.swing.JComboBox cb_costos;
    private javax.swing.JComboBox cb_item;
    private javax.swing.JComboBox cb_linea;
    private javax.swing.JComboBox cb_otrotipocom;
    private javax.swing.JComboBox cb_registros;
    private javax.swing.JComboBox cb_registros1;
    private javax.swing.JComboBox cb_tc;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JComboBox cb_tipo_doc;
    private javax.swing.JComboBox cb_vehiculo;
    private javax.swing.JCheckBox ck_box_ven;
    private com.toedter.calendar.JDateChooser dc_inicio;
    private com.toedter.calendar.JDateChooser dc_ven;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_encabezado;
    private javax.swing.JPanel panel_oculto;
    private javax.swing.JTabbedPane tp_general;
    private javax.swing.JTextField txt_aceite_dir;
    private javax.swing.JTextField txt_alternador;
    private javax.swing.JTextField txt_can_pasa;
    private javax.swing.JButton txt_cancelar1;
    private javax.swing.JTextField txt_cap_ace_dif;
    private javax.swing.JTextField txt_cap_aceite_motor;
    private javax.swing.JTextField txt_cap_cam;
    private javax.swing.JTextField txt_cap_refri;
    private javax.swing.JTextField txt_cap_tan_com;
    private javax.swing.JTextField txt_carroceria;
    private javax.swing.JTextField txt_chasis;
    private javax.swing.JTextField txt_cilindraje;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_motor;
    private javax.swing.JTextField txt_motor_arran;
    private javax.swing.JTextField txt_ndoc;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_presi_inf;
    private javax.swing.JTextField txt_ref_bateria;
    private javax.swing.JTextField txt_ref_llanta;
    private javax.swing.JTextField txt_rin;
    private javax.swing.JTextField txt_serie;
    private javax.swing.JTextField txt_tipo_cambi;
    private javax.swing.JTextField txt_tipo_dif;
    private javax.swing.JTextField txt_tipo_dir;
    private javax.swing.JTextField txt_vel_marcha_min;
    // End of variables declaration//GEN-END:variables

      public void cargarItemLinea()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemLinea();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_linea.addItem(lista.get(i));
            }
        }
    }
      
      public void limpiar()
      {
         txt_placa.setText("");
         
         
         txt_carroceria.setText("");
         txt_modelo.setText("");
         txt_serie.setText("");
         txt_chasis.setText("");
         txt_motor.setText("");
         txt_color.setText("");
         txt_cilindraje.setText("");
         txt_can_pasa.setText("");
         txt_motor_arran.setText("");
         txt_vel_marcha_min.setText("");
         txt_peso.setText("");
         txt_cap_aceite_motor.setText("");
         txt_cap_refri.setText("");
         txt_cap_tan_com.setText("");
         txt_tipo_cambi.setText("");
         txt_cap_cam.setText("");
         txt_tipo_dir.setText("");
         txt_aceite_dir.setText("");
         txt_tipo_dif.setText("");
         txt_cap_ace_dif.setText("");
         txt_rin.setText("");
         txt_ref_llanta.setText("");
         txt_presi_inf.setText("");
         txt_ref_bateria.setText("");
         txt_alternador.setText("");
      }
      
      
          public void cargarItemVehiculo()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarItemVehiculo();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_vehiculo.addItem(lista.get(i));
                cb_registros.addItem(lista.get(i));
                cb_registros1.addItem(lista.get(i));
            }
        }
    }
          
          
     
  
          
          
          
          
            public void cargarItemTipoDoc()
    {
        ControllerItemList control=new ControllerItemList();
        
        ArrayList lista=control.listarIteTipoDoc();
        
        if (lista!=null)
        {
            int size=lista.size();
            
            for(int i=0; i<size; i++)
            {
                cb_tipo_doc.addItem(lista.get(i));
                
            }
        }
    }

    public void buscarFichaTecnica(int id_vehiculo)
    {
        
        
       String tipo_carroceria="", modelo="",serie="", chasis="", n_motor="", color="", cilindraje="", n_pasajeros="", motor_arranque="", v_marcha_minima="", peso_bruto="", cap_aceite_motor="", cap_refrigerante="",cap_tan_combustible="",tipo_caja_cambios="",cap_caja_cambios="",tipo_direccion="",cap_aceite_direccion="", tipo_diferencial="",cap_aceite_diferencial="", n_rin_rueda="", referencia_llanta="", presion_inflado="", referencia_bateria="",alternador=""; 

        ResultSet obj=conexion.executeQuery("SELECT * FROM utilidades.ficha_tecnica_vehiculo_equipo WHERE id_vehiculo="+id_vehiculo+"");
        
        
        
        try {
            if(obj.next()==true)
            {
                tipo_carroceria=obj.getString("tipo_carroceria");
                modelo=obj.getString("modelo");
                serie=obj.getString("serie");
                chasis=obj.getString("chasis");
                n_motor=obj.getString("n_motor");
                color=obj.getString("color");
                cilindraje=obj.getString("cilindraje");
                n_pasajeros=obj.getString("n_pasajeros");
                motor_arranque=obj.getString("motor_arranque");
                v_marcha_minima=obj.getString("v_marcha_minima");
                peso_bruto=obj.getString("peso_bruto");
                cap_aceite_motor=obj.getString("cap_aceite_motor");
                cap_refrigerante=obj.getString("cap_refrigerante");
                cap_tan_combustible=obj.getString("cap_tan_combustible");
                tipo_caja_cambios=obj.getString("tipo_caja_cambios");
                cap_caja_cambios=obj.getString("cap_caja_cambios");
                tipo_direccion=obj.getString("tipo_direccion");
                cap_aceite_direccion=obj.getString("cap_aceite_direccion");
                tipo_diferencial=obj.getString("tipo_diferencial");
                cap_aceite_diferencial=obj.getString("cap_aceite_diferencial");
                n_rin_rueda=obj.getString("n_rin_rueda");
                referencia_llanta=obj.getString("referencia_llanta");
                presion_inflado=obj.getString("presion_inflado");
                referencia_bateria=obj.getString("referencia_bateria");
                alternador=obj.getString("alternador");
                id_ficha=obj.getInt("id_ficha");
                
                System.out.println(id_ficha);
                
                        
            }
            
            txt_carroceria.setText(tipo_carroceria);
         txt_modelo.setText(modelo);
         txt_serie.setText(serie);
         txt_chasis.setText(chasis);
         txt_motor.setText(n_motor);
         txt_color.setText(color);
         txt_cilindraje.setText(cilindraje);
         txt_can_pasa.setText(n_pasajeros);
         txt_motor_arran.setText(motor_arranque);
         txt_vel_marcha_min.setText(v_marcha_minima);
         txt_peso.setText(peso_bruto);
         txt_cap_aceite_motor.setText(cap_aceite_motor);
         txt_cap_refri.setText(cap_refrigerante);
         txt_cap_tan_com.setText(cap_tan_combustible);
         txt_tipo_cambi.setText(tipo_caja_cambios);
         txt_cap_cam.setText(cap_caja_cambios);
         txt_tipo_dir.setText(tipo_direccion);
         txt_aceite_dir.setText(cap_aceite_direccion);
         txt_tipo_dif.setText(tipo_diferencial);
         txt_cap_ace_dif.setText(cap_aceite_diferencial);
         txt_rin.setText(n_rin_rueda);
         txt_ref_llanta.setText(referencia_llanta);
         txt_presi_inf.setText(presion_inflado);
         txt_ref_bateria.setText(referencia_bateria);
         txt_alternador.setText(alternador);
     
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(JIFVehiculosEquipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
         
     private void Actualizar_lista()
    {
        
        Vehiculo v=(Vehiculo) cb_registros.getSelectedItem();
        id_vehiculo_img=v.getId_vehiculo();
        this.modListaImagen.clear();
        this.modListaImagen = mi.Lista_Imagenes2(id_vehiculo_img);
        this.Lista_Imagenes.setModel(modListaImagen);
    }
     
      private void Actualizar_lista2()
    {
        
        Vehiculo v=(Vehiculo) cb_registros1.getSelectedItem();
        id_vehiculo_doc=v.getId_vehiculo();
        this.modListaImagen.clear();
        this.modListaImagen = mi.Listar_doc(id_vehiculo_doc);
        this.Lista_Imagenes1.setModel(modListaImagen);
    }

      //Genera un código unico para la imagen
    private String GenerarCodigo()
    {
        SimpleDateFormat sdf= new SimpleDateFormat("hhmmss");
        return sdf.format(new Date());
    }


}
